[숫자 야구 게임] 복수방 모두한 제출합니다.
REVENGE-WOOTECO/java-baseball-precourse pull request #1
Opened 2021-11-27 15:27 UTC by DuhanMo

2021-11-28 14:04 UTC, bperhaps requested changes
안녕하세요 모두한님 :) 우아한테크코스 3기 손너잘입니다.
소스 정말 잘 읽었어요! 열심히 구현해 주신게 코드에서 느껴집니다 💯 

리뷰는 프리코스과정을 기반으로 작성해봤어요. 나머지 프리코스도 계속 따라와 주신다면 더욱 많은 정보 드릴 수 있으니 끝까지 해주셨으면 하는 바람입니다 :)

작은 리뷰들은 comment로 남겼고 전체적인 리뷰를 먼저 드리겠습니다.

코드를 봤을 때 컨벤션과 같은 코드의 스타일이 C를 많이 닮아있다고 느껴요. 절차지향적 코딩을 많이 하신분인 것 같아요 :)

프리코스 뒤에서가서도 조금씩 배우겠지만 아래 글을 읽어보고 절차지향과 객체지향의 작은 차이에 대해서 생각해 보시고 다음 코드 작성에서 반영해보시면 좋을 것 같아요!

[객체지향과 절차지향](https://bperhaps.tistory.com/entry/%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5%EA%B3%BC-%EC%A0%88%EC%B0%A8%EC%A7%80%ED%96%A5%EC%9D%80-%EB%AC%B4%EC%97%87%EC%9D%B4-%EB%8B%A4%EB%A5%BC%EA%B9%8C)

또한, 객체의 접근제어자를 생략하시는 경우가 많으시던데, 접근제어자의 역활과 그렇게 분리되어있는 이유에 대해서도 공부해보면 좋을 것 같습니다 ;)

정말 수고해주셨고 궁금하신점 있으시면 언제든 댓글 남겨주세요!
코드 수정 후 재 PR 부탁드립니다 감사합니다!

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +                && input.charAt(1) != input.charAt(2);
input으로 들어오는 숫자들이 서로 다른 숫자를 가지고 있는것을 검증하기 위한 부분이군요!!
만일 게임의 규칙이 변경되어 4개의 숫자를 입력받고, 또 5개의 숫자를 입력받도록 되면 이 로직은 어떻게 수정될까요??

이런 중복을 확인하는 방법중 우리가 사용할 수 있는 자료구조가 무엇이 있는지 확인해보고 적용해 보면 좋을 것 같습니다 :)

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +    }
입력의 길이를 확인하는 부분이네요 :) 만일 게임 규칙이 변경되어서 3이 아니라 4, 5로 변경됐을때 코드가 이렇게 작성되어 있다면 어떤 문제가 있을까요? 또, 3이라는 숫자가 다른곳에서도 쓰이게 된다면 어떤 문제가 있을까요?
3 을 한번 상수로 추출해볼까요??

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +    }
정규표현식을 이용하여 깔끔하게 작성해 주셨네요 👍 
Pattern을 이용한 정규표현식 사용은 생각보다 큰 연산 비용을 잡아먹는다고 알고 있습니다. 수십만, 수백만의 사용자가 위 프로그램을 사용한다고 가정했을 때 매 input마다 Pattern을 사용한다면, 성능상으로 문제가 발생할 가능성이 있습니다.

![image](https://user-images.githubusercontent.com/33603557/143769679-43cb0904-d8de-4636-8fdd-b413c3cd0e8f.png)

![image](https://user-images.githubusercontent.com/33603557/143769689-cfc27b6f-a1b5-473f-9232-213078d25564.png)

위에서 보시듯, `Pattern.compile()`은 매번 새로운 Pattern 객체를 생성하고 정규표현식을 compile하거든요 :)

Pattern도 상수로 만들어서 같은 객체를 돌려쓰도록 하는게 어떨까요?

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +        }
validate를 깔끔하게 잘 분리해 주셨어요 👍 
약간의 취향차이이긴 하지만 Exception을 throw하는 로직도 validate### 메서드 안으로 밀어 넣는건 어떠신가요? 
validation로직이 많아지고 특정 validation 상황에서 발생해야 하는 예외가 변경됐을 때 해당 validation 메서드에서 변경하는 것이 이 로직에서 특정 메서드를 찾아서 변경하는것 보다 유지보수하기에 좋다고 생각돼서요 :)
이거는 저의 개인적인 생각이니 꼭 반영하지 않으셔도 좋습니다 :)

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +        return Arrays.stream(input.split("")).map(Integer::parseInt).collect(Collectors.toList());
```suggestion
        return Arrays.stream(input.split(DELIMITER))
            .map(Integer::parseInt)
            .collect(toList());
```
스트림을 아주 잘 사용해 주셨어요!
일반적으로 스트림을 사용할때에는 위와같은 방식으로 가독성을 높혀줍니다. 
stream을 사용하는 이유중 중요한 요소는 `가독성이 좋다.` 도 있거든요! 이러한 이점을 살리기 위한 개행을 준수해 주는것도 좋아 보입니다!
또한 위 로직을 메서드로 분리할 수 있을 것 같아요!

- `""`의 경우로 구분자의 일종이니 상수로 만들어 보시는게 어떠신가요?
- Collectors.toList()와 같은 메서드을 그대로 사용하면 읽을 소스가 길어져서 가독성을 해칠 수 있습니다! static import에 대해서 알아보시면 좋을 것 같아요 :)

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +    public static final int BASE_COUNT = 3;
```suggestion
    private static final int BASE_COUNT = 3;
```

매직넘버의 상수화 매우 좋습니다 💯 
하지만 접근제어자가 public 으로 되어있네요.  모든 클래스에 있는 필드변수들을 최대한 private으로 닫아주는게 좋아요 캡슐화와 응집도, 결합도라는 것과 관련이 있는데, 지금은 이해하기 어려울 수 있으니 슬쩍 한번 읽어보시는것도 좋아 보입니다 :)

https://bperhaps.tistory.com/entry/%EC%BA%A1%EC%8A%90%ED%99%94%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80-%EC%96%B4%EB%96%A4-%EC%9D%B4%EC%A0%90%EC%9D%B4-%EC%9E%88%EB%8A%94%EA%B0%80

BASE_COUNT를 다른곳에서도 사용하는 것 같은데, private으로 닫으면 다른곳에서는 이 상수를 사용 못하겠네요. 그렇다면 다른 방법은 무엇이 있을까요? 한번 생각해보죠 :)

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +    List<Integer> input() {
접근제어자가 default로 되어 있군요! 혹시 이렇게 하신 특별한 이유가 있을까요?

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +    List<Integer> initComputer() {
접근제어자가 default로 되어 있군요! 혹시 이렇게 하신 특별한 이유가 있을까요?

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +        List<Integer> computer = new ArrayList<>(BASE_COUNT);
capacity를 고려하는 세심함 멋집니다 👍

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Application.java
> +            } else if (!result.equals("")) {
```suggestion
            } else if (!result.isEmpty()) {
```

비어있는것을 확인할때는 isEmpty()를 사용하시는 것이 가독성이 더욱 좋습니다 :)

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Game.java
> +    String play(List<Integer> input, List<Integer> computer) {
play라는 함수에서 너무 많은 기능을 담당하고 있는 것 같아요! 한번 메소드로 분리해보는거 어떨까요?? :)
또한 접근제어자가를 Default로 하신 이유가 있을까요??

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Game.java
> +        String result = "";
result를 미리 선언할 필요가 있을지 한번 생각해 보는게 좋을 것 같아요! 아래 로직을 조금만 손본다면 result라는 변수 자체가 필요 없어질 수도 있다는 생각이 듭니다 :)

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Game.java
> +        }
strike와 ball을 count하는 로직이군요:)
이 부분을 메서드로 분리할 수 있지 않을까요?

2021-11-28 14:04 UTC, bperhaps commented on src/main/java/baseball/Game.java
> +        return result;
게임의 결과를 판별하는 로직으로 보이네요 :) 
이 부분 또한 메서드로 분리할 수 있지 않을까요??

2021-11-28 14:04 UTC, bperhaps commented on README.md
> +6. 정답 후 재시작/종료 구분 처리
요구사항을 아주 잘 작성해 주셨어요 💯 

혹시 아실수도 있지만, markdown 문법중에는 checkbox로 제공되고 있답니다.
`- [ ]` 를 사용하면 사용할 수 있는데요, 저같은 경우는 체크박으로 구현기능목록을 관리하는걸 선호해요. 제가 무엇을 개발했는지, 무엇을 아직 개발하지 못했는지 확인하기 더욱 편하거든요!

모두한님도 한번 해보시는걸 추천드립니다 :)

- [x] 리뷰하기

2021-11-28 15:07 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +                && input.charAt(1) != input.charAt(2);
네 단순히 3이라는 숫자에 매몰되어서 그런방식의 확장성을 생각하지 못했습니다!

숫자 개수에 상관없이 중복확인을 할 수 있는 자료구조와 로직을 생각해보겠습니다!

2021-11-28 15:09 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +    }
네 BASE_COUNT라는 상수로 추출을 해봤었는데 이 부분에 적용시키지 못했네요
좀 더 꼼꼼히 코드를 짜는 습관을 길러보겠습니다!

2021-11-28 15:12 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +    }
성능부분 리뷰 정말 감사합니다!

api를 이용할 때에 단순히 이용만 하는 것이 아니라, 
메서드의 작동방식에 대해서, 또 성능에 대해서도 생각해 볼 수 있는 식견 주셔서 감사합니다!!

2021-11-28 15:16 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +        }
좋은 의견 감사합니다😄

저도 손너잘님이 말씀해주신 부분과 위 방식 중에 고민했었는데요

특정 validate 메서드 안에 throw하는 부분이 말씀하신 것처럼 유지보수에 좀 더 용이할 것 같습니다!

2021-11-28 15:20 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +        return Arrays.stream(input.split("")).map(Integer::parseInt).collect(Collectors.toList());
감사합니다

또 꼼꼼히 체크하지 못하는 습관이 나온 것 같습니다.

개행준수와 함께 가독성을 향상한 코드를 짜기위해 노력하겠습니다!

""의 상수화와 static import, 개행 준수 적용시켜보겠습니다😀

2021-11-28 15:22 UTC, DuhanMo commented on src/main/java/baseball/Game.java
> +    String play(List<Integer> input, List<Integer> computer) {
play 메서드의 기능을 좀 더 나누어 보도록하겠습니다!

접근제어자를 Default로 사용한 이유는 같은 패키지 내부에서 사용할 것이기 때문에,

최대한 fit 하게 접근 제어자를 선언해 보았습니다!

따로 public으로 개방시킬 이유를 찾지 못해서였습니다.. 혹시 이부분에 대해서 제가 오해를 하고 있는게 있을까요?

알려주신다면 정말 감사하겠습니다!!

2021-11-28 15:23 UTC, DuhanMo commented on src/main/java/baseball/Game.java
> +        String result = "";
넵 변수선언에 조금 더 신경을 써보겠습니다! 동시에 아래 로직도 그에 맞게 손을 봐야겠군요😄

2021-11-28 15:25 UTC, DuhanMo commented on src/main/java/baseball/Game.java
> +        }
네,
메서드로 분리할 수 있는 충분한 기능인것 같습니다!!
분리해보도록 하겠습니다!

2021-11-28 15:25 UTC, DuhanMo commented on src/main/java/baseball/Game.java
> +        return result;
네!
결과 판별이라는 기능의 또다른 메서드로 추출을 하겠습니다

2021-11-28 15:27 UTC, DuhanMo commented on README.md
> +6. 정답 후 재시작/종료 구분 처리
효율적인 마크다운 문법 정말 감사드립니다ㅎㅎ
다음 코스에는 꼭 이용하겠습니다!

2021-11-28 15:32 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +    public static final int BASE_COUNT = 3;
다른 곳에서 사용하기 위해 public으로 선언을 했던 것인데,

오히려 private으로 닫고 다른 방식을 이용할 수 있는 부분을 생각치 못했네요!!

상수를 캡슐화한 후에 재이용하는 방식을 찾아보겠습니다ㅎㅎ

2021-11-28 15:33 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +    List<Integer> initComputer() {
접근제어자를 Default로 사용한 이유는 같은 패키지 내부에서 사용할 것이기 때문에,

최대한 fit(?) 하게 접근 제어자를 선언해 보았습니다!

따로 public으로 개방시킬 이유를 찾지 못해서였습니다.. 혹시 이부분에 대해서 제가 오해를 하고 있는게 있을까요?

알려주신다면 정말 감사하겠습니다!!

2021-11-28 15:34 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +    List<Integer> input() {
접근제어자를 Default로 사용한 이유는 같은 패키지 내부에서 사용할 것이기 때문에,

최대한 fit(?) 하게 접근 제어자를 선언해 보았습니다!

따로 public으로 개방시킬 이유를 찾지 못해서였습니다.. 혹시 이부분에 대해서 제가 오해를 하고 있는게 있을까요?

알려주신다면 정말 감사하겠습니다!!

2021-11-28 15:34 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +        List<Integer> computer = new ArrayList<>(BASE_COUNT);
감사합니다!😊

2021-11-28 15:34 UTC, DuhanMo commented on src/main/java/baseball/Application.java
> +            } else if (!result.equals("")) {
좋은 정보 감사합니다!! 

비어있는 문자를 확인할 땐 isEmpty()를 이용하겠습니다!

2021-11-28 15:41 UTC, DuhanMo commented
우선 소중한 시간 내주셔서 리뷰해주신 점 너무나 감사드립니다!
""의 상수화, static import 이용, isEmpty(), 코드의 개행, 메서드의 실제 작동원리(Pattern), 메서드별 기능의 확실한 분리, 마크다운꿀팁 등등..
정말 감사합니다😌

사실 이렇게 누군가의 코드리뷰를 받아본적이 없어서 해주신 리뷰를 보면서 정말 감탄이 나고 웃음이 나왔습니다😊
손너잘님의 생각을 흡수하고 또 확장되는 기분입니다

손너잘님의 테스트코드의 최적화라는 발표 보면서 저도 저렇게 되고싶다라는 생각을 갖고 있었는데,
마침 그분이 오셔서 놀랐습니다 ㅎㅎ

추천해주신 책 꼭 읽어보겠습니다!
다시 한번 감사드립니다(_ _)

2021-11-29 07:53 UTC, bperhaps commented on src/main/java/baseball/Game.java
> +    String play(List<Integer> input, List<Integer> computer) {
@DuhanMo 안녕하세요 모두한님! 접근제어가 관련 질문을 주셨는데요! 사실 Default를 접근제어자로 사용하는 경우는 특별한 API를 생성할때는 제외하고는 많이 보지 못했습니다. 사용한다고 하더라고 class 단위로 많이 사용하구요 :)
사실, 객체의 책임과 역활이라는 것을 공부해 보시면 이런부분을 더욱 잘 느끼실 수 있을 것 같은데요 메서드의 접근데어지를 package-private으로 하기 보다는 적절한 역할(인터페이스)를 더욱 중요시 설계하시는게 중요합니다. 객체지향 공부를 하면서 천천히 알아가시게 될 것이니 알아만 주시면 좋을 것 같습니다 :)

2021-12-02 07:58 UTC, bperhaps approved these changes
안녕하세요! 수정해주신 코드 잘 읽었습니다!
정말 깔끔하게 잘 구현해 주셨어요 👍
몇가지 코멘트 남겼으니 한번 확인해 주시면 좋을 것 같아요 :)
프리코스 단계가 올라가면서 몇가지 제약사항이 생기고, 그 제약사항을 지키기 위해서 점점 생각할 부분이 많아질꺼에요. 하지만 그걸 통해 얻어가는 것이 더 많을거에요.
프리코스 1단계는 여기서 merge하도록 하겠습니다. 정말 수고하셨습니다 💯

2021-12-02 07:58 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +    }
getter를 이용하여 문제를 해결하셨군요!!
사실 이렇게 getter를 사용하는것과 public 상수를 직접 호출하는것에는 큰 차이가 없답니다 ㅎㅎ...

제가 의도드린 방법은 이런 전역으로 쓰이는 상수는 따로 enum등으로 빼서 관리하는 것 이었어요! 이런 이유는 객체간의 결합도와 관련이 있는데, 지금은 중요하지 않으니 '결합도와 응집도' 에 대해서 간단히만 알아보고 가시면 좋을 것 같습니다 :)

2021-12-02 07:58 UTC, bperhaps commented on src/main/java/baseball/Util.java
> +    }
set을 사용하셨군요!! 정말 좋습니다 👍

2021-12-02 07:58 UTC, bperhaps commented on src/main/java/baseball/Game.java
> +    private static final String NOTHING = "nothing";
필드를 선언하는 순서에도 컨벤션이 있는것 아시나요??

보통 상수를 가장 상단에 배치합니다! 한번 알아보시면 좋을 것 같아요!

2021-12-02 07:58 UTC, merged

2021-12-03 02:18 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +    }
넵 해당 키워드로 학습해보고 enum과 getter호출의 차이를 알아보겠습니다!

2021-12-03 02:18 UTC, DuhanMo commented on src/main/java/baseball/Util.java
> +    }
감사합니다!

2021-12-03 02:19 UTC, DuhanMo commented on src/main/java/baseball/Game.java
> +    private static final String NOTHING = "nothing";
넵 필드선언 컨벤션도 공부하겠습니다:) 좋은 코멘트 감사합니다