[숫자 야구 게임] y 미션 제출합니다
REVENGE-WOOTECO/java-baseball-precourse pull request #2
Opened 2021-11-27 16:27 UTC by jiyoung-Heo

2021-11-28 22:59 UTC, sihyung92 requested changes
수고하셨습니다~~!! 
컨벤션을 지켜서 코딩하시려고 노력한 흔적이 보여서 좋았어요 👏👏👏
궁금한거 있으면 그 어떤 거 라도 좋으니 적어주셔요!!

2021-11-28 22:59 UTC, sihyung92 commented on README.md
> +   + 예외처리
예외처리에 대한 부분도 따로 리드미를 작성해주신 부분 좋습니다 :) 

꼼꼼한 리드미 작성의 중요성에 대한 부분을 개인적인 경험에 비추어 말씀 드리면,
하나의 과제에 집중할 때는 '리드미 작성' 자체가 귀찮음이나 불편함으로 느껴질 때도 있는데요(이미 다 아는 내용을 글로 또? 보여주기용인가?), 미션과 사이드 프로젝트, 메인프로젝트를 동시에 진행하다보면 3일만 한 프로젝트를 안봐도 새하얗게 잊게 되더라고요🤪 그때 미리 작성해둔 리드미가 한 줄기 빛이 되어주었답니다 😊

그렇다면 해당 리드미는 제가 아닌 다른 사람이 제 코드를 손보기 위해 봐도 매우 유용한 자료가 될 수 있겠단 생각도 들었고요~~

2021-11-28 22:59 UTC, sihyung92 commented on build.gradle
> +[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
해당 내용은 어떤 연유로 추가해주셨나요? 🙂 콘솔에서 한글이 깨진 문제라면, IDE 환경설정을 통해 수정할 수 있습니다. Intellij 기준 Encoding으로 검색해보셔요

![image](https://user-images.githubusercontent.com/51393021/143787506-de61a5a8-48c5-4597-9400-4ed03bbeb416.png)
![image](https://user-images.githubusercontent.com/51393021/143787534-525d4013-16c9-4f66-a647-8eb295d4e45a.png)

2021-11-28 22:59 UTC, sihyung92 commented on README.md
> +   + 예외처리
그리고 체크박스를 통해 매 기능을 커밋하실 때 마다 같이 체크해주신 부분도 좋습니다. 위에 말씀드린거에 이어, 실질적으로 유용한 문서가 되려면 실제 어플리케이션 동작을 반영한 '살아있는 문서'가 되야합니다.

💎 살아있는 문서를 만들기 위한 꿀팁 💎
1. 시작할 때 모든 기능 목록을 완벽하게 정리해야 한다는 부담을 가지기 보다 기능을 구현하면서 문서를
계속 업데이트한다.
2. 클래스 설계와 구현, 함수(메소드) 설계와 구현과 같이 너무 상세하게 작성하지 않는다.
 클래스 이름, 함수(메소드) input/output은 언제든지 변경될 수 있기 때문이다.
3. 예외처리에 대한 부분도 작성한다. 예외처리는 특히 시작단계에선 모두 찾기 힘들기 때문에 구현하면서 추가해나간다.

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	 */
문서화 주석 작성하시느라 수고하셨어요!!! 
그러나 가급적 문서화 주석보단 변수 이름, 함수(메소드)이름, 클래스 이름을 통해 의도를 드러내는 것을 권장합니다. 

우테코 바이블(?)인 클린 코드엔 주석에 대한 챕터가 있는데요, 
https://nesoy.github.io/articles/2018-01/CleanCode-Comment
해당 포스팅엔 나와있지 않지만 저자인 엉클밥은 주석이 없는 것을 최우선하고, 차악으로 정말 어쩔수 없는 경우에만 주석을 작성할 것을 권합니다.

> 코드에 주석을 추가하는 일반적인 이유는 코드 품질이 나쁘기 때문이다. 깔끔하고 주석이 거의 없는 코드가, 복잡하고 어수선하며 주석이 많이 달린 코드보다 훨씬 좋다. 주석으로 설명하려 애쓰는 대신에 그 난장판을 깨끗이 치우는 데 시간을 보내라!

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
>  public class Application {
현재 제출해주신 코드에선 하나의 클래스에서 모든 기능이 처리되고 있는데요, 클래스를 분리하는 연습을 미리 하는 것을 추천드려요 :)
클래스를 분리하는 기준은 '비슷한 기능을 하는가? -> 재사용 할 가능성이 있는가?' 를 기준으로 나눠주시면 좋을 것 같아요. 

이는 객체지향 5원칙 중 하나인 '책임분리원칙(SRP)' 와도 연관있는데, 마침 4기톡방 방장이 정리를 잘 해놔서 달아놓겠습니다 🤣
https://steady-coding.tistory.com/370

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			ArrayList<Integer> answerNumber = application.makeAnswerNumber();
ArrayList 타입으로 할당을 받고 있는데요, List 인터페이스 타입으로 받는 것을 권장합니다. 
상위 인터페이스 타입으로 할당받는 것엔 어떤 장점이 있을까요? 
그리고 그러면 List 인터페이스엔 명시되어 있고 ArrayList에만 구현되어있는 메소드는 사용하지 못하는 데 그런 상황에는 어떻게 할까요??

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	public boolean isStartOver() {
해당 메소드에서 입력을 받는 부분(inputNumber)과, 입력값을 검증하는 부분은 메소드 분리하는게 어떨까요?

왜냐하면 저만해도 방금 isStartOver()가 순수하게 boolean을 리턴할거라 예상하고 main while문의 flag로 isStartOver를 넣었다가 오류를 만났거든요 :) (테스트를 즉시 실행시켜봄으로써 바로 오류를 확인하였습니다, 테스트의 중요성이기도 하네요!)

다른 개발자와 이런 오해를 줄이기 위해 하나의 메소드는 하나의 역할만! 하도록 구현해보시는 건 어떨까용~~

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			if (answerNumber.size() == 3) {
해당 플래그가 while 조건문으로 이동해도 될것 같네요 :)

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			} else {
else는 **가능한** 지양하는 편입니다. 

만약 answerNumber에 4보다 커야한다는 요구사항이 추가된다면?
```
else if(randomNumber > 4) {
  // do Something
} else...
```
요렇게 되겠죠? 무언가 요구사항이 하나씩 추가될때마다 if, else 블록은 점점 커질겁니다. 종래엔 나 자신도 확인하기 힘든 코드가 될 것이고요🐒


else 블록을 없애는 방법은 '메소드 분리', '추상화' 등 다양한 방법이 있을텐데, 요 else블록은 어떻게 없앨 수 있을지 생각해 보시는 것도 좋겠네요 :)

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	public boolean handleException(String inputNumber) {
메소드명은 handleException인데, 예외에 대한 핸들링은 inputNumber에서 해주고 있네요 :) 해당 메소드는 받은 숫자값을 검증하여 알맞은지 확인해주는 역할인데, 적절한 네이밍은 없을까요?? 😌

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			int randomNumber = Randoms.pickNumberInRange(1, 9);
비즈니스적 의미를 담고 있는 상수값을 매직넘버라고 부르는데요, 이 라인의 int값 1,9에 해당합니다! 
아래 포스팅 참고하셔서 상수로 선언하여 활용해보시는 건 어떨까용!
매직넘버를 상수화할 땐 의미를 잘 담는 게 좋습니다. 
```java
private static final int ONE = 1; // 상수화를 한 의미가 없음
private static final int MIN_RANGE = 1; // good
```
https://hoonmaro.tistory.com/44

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			if (c >= '1' && c <= '9') {
매직넘버! 👀

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			} while (isAnswer == false);
코드 전체적으로 == false 비교를 하는 내용이 많은데요, 부정연산자(`!`) 를 활용 안 하시는 이유가 있을까요?👀 (진짜 궁금해서 여쭤보는거에요~~!!! 꼽주는거 아니니 안심하셔요)

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			if (answer.equals("") == false) {
answer.equals("") 은 String의 메소드를 사용할 수 있습니다 :) 
```java
answer.isEmpty()
```

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	public boolean compareNumber(ArrayList<Integer> answerNumber, String inputNumber) {
해당 메소드에 inputNumber를 String이 아니라 int나 Integer 자료구조로 치환해서 받는 건 어떨까요? 
inputNumber()쪽에서 입력받은 String이 '숫자모음인지' 에 대한 검증을 해주셨는데, 이 메소드에서 String으로 받으면 값에 대한 검증을 다시 한번 진행해야합니다. 왜냐하면 이 메소드를 호출하는 개발자가 '검증된' inputNumber를 넘겨줄거란 확신이 없으니까요.. '_' (버그가능성!)

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	public int ballCount(ArrayList<Integer> answerNumber, String inputNumber) {
compareNumber()메소드와 동일한 리뷰입니다 :) 적용하면 로직도 한결 가벼워질 것 같네요

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			if (answerNumber.contains(Integer.parseInt(inputNumberArray[j]))
compareNumber쪽에서 말씀드린 버그가능성과 연관된 파트입니다. Integer.parseInt()에 마우스를 올리고 가만히 귀기울여 보시면 docs를 띄워주는데요, 정수값이 아니면 NumberFormatException이 발생합니다(아시겠지만!) 
![image](https://user-images.githubusercontent.com/51393021/143789648-b6668390-f7bf-45ae-98c5-1007a05e9fd2.png)

2021-11-28 22:59 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	public int strikeCount(ArrayList<Integer> answerNumber, String inputNumber) {
compareNumber, ballCount 메소드와 동일한 리뷰입니다

2021-11-29 07:26 UTC, jiyoung-Heo commented on build.gradle
> +[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
저렇게 설정되어있는 상태인데도 
인텔리제이 내의 터미널로 테스트를 진행했더니 
한글깨짐이 발생하더라구요,, 그래서 추가해줬습니다!

2021-11-29 07:35 UTC, jiyoung-Heo commented on src/main/java/baseball/Application.java
> +	 */
주석을 작성해야 협업시에 편하다고 생각해서 다 작성했는데 좋은방법이 아니었군요..!!
주석 제거하고 이름을 조금 더 신경써서 수정하도록 하겠습니다.

2021-11-29 07:41 UTC, jiyoung-Heo commented on src/main/java/baseball/Application.java
>  public class Application {
네 맞습니다
프로젝트 할 때 마다 시간에 쫒겨서 코드를 짜다 보니
객체지향의 원칙을 잘 지키지 못했는데요, 

이번 미션에도 클래스를 분리해야 하나 고민을 했었는데 한번도 해보지 않았다보니 감이 안잡히더라구요 🤣
좋은지적과 조언 감사합니다 !! 클래스분리 연습 해보도록하겠습니다.

2021-11-29 08:00 UTC, jiyoung-Heo commented on src/main/java/baseball/Application.java
> +	public boolean isStartOver() {
헉 맞습니다 두개의 역할을 하네요,, 수정하겠습니다!

2021-11-29 08:45 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	 */
협업시에 가장 필요한건 '내가 이 팀원의 입장이라면' 생각해보는 마음이라고 개인적으로 생각합니다아
주석 또한 유지보수의 대상(비용)이 될 수 있기에 덜어낼 수 있다면 더는 게 좋겠지만, 만약 가독성이 충분하지 않은 상황에서 개선할 자신이 없다면 주석을 다는 것도 팀원을 위한 친절함 이라고 생각합니다 :)

2021-11-29 08:48 UTC, jiyoung-Heo commented on README.md
> +   + 예외처리
저는 이번 미션을 계기로 처음 리드미를 작성해 보았는데 처음에는 왜 해야하지? 라는 생각을 가지고 시작했습니다. 
그러나 하다보니 채워가는 재미도 있고 어느 부분을 구현하면 되는지 어떤식으로 구현할지 한눈에 확인할 수 있어서 좋았습니다.
말씀대로 꼼꼼한 리드미 작성을 통해 잊지 않고 프로젝트를 이어나갈 수 있겠다는것에 공감했습니다.

이번 피드백도 리드미에 추가하여 하나씩 고쳐나갈계획입니다

2021-11-29 08:51 UTC, jiyoung-Heo commented on src/main/java/baseball/Application.java
> +			} while (isAnswer == false);
부정연산자를 쓰니까 true랑 한눈에 구분하기 어렵더라구요
 !가 너무 작아서,,ㅎㅎ
 false로 써주면 한눈에 확인할 수 있어서 이렇게 쓰고 있습니다.

혹시 == false 보다 부정연산자를 사용하는게 더 클린한 코드인가요??

2021-12-01 11:33 UTC, jiyoung-Heo commented on src/main/java/baseball/Application.java
> +	public boolean handleException(String inputNumber) {
해당 메소드는 hasException 으로 이름을 수정하였습니다.!
또한 inputNumber 메소드가 숫자를 입력받는 기능과 예외 핸들링을 하는 두가지 기능으로 이루어져 있어 메소드를 분리하겠습니다

2021-12-01 11:45 UTC, jiyoung-Heo commented on src/main/java/baseball/Application.java
> +	public boolean compareNumber(ArrayList<Integer> answerNumber, String inputNumber) {
아하 저는 당연히 inputNumber() 이후에 inputNumber()에서 검증된 값만 compareNumber()에 들어간다고 생각하고 코드를 작성하였습니다. 
말씀대로 개발자가 임의의 값을 inputNumber에 넣어줄것이라는 생각을 전혀 하지 못했습니다 ,, 이마를 탁 치게 되네요 🙂

2021-12-26 13:09 UTC, jiyoung-Heo commented
코드 리뷰 수정 이후  어떻게 진행되는지 몰라서 comment 닫았었는데 2주차 피드백 받다보니 브랜치에 머지해주신다는것을 알았습니다... 

리뷰 해 주신 부분은 모두 수정한 상태입니다. 

늦었지만 한번 체크해주실수 있으실까요..?

2021-12-26 14:40 UTC, sihyung92 commented
ㅎㅎㅎ 그럼요그럼요
다만 제가 개인적으로 휴가 중이라 29일 정도에 할 수 있을 것 같아요! 그 이후에 다시 확인하고 코멘트 드릴게요 :)

2021-12-29 13:12 UTC, sihyung92 requested changes
자잘한 리뷰 몇 가지 남겼습니다 :p
메서드를 잘게 쪼개는 연습을 하셨는데, 자바의 핵심은 클래스 분리이기 때문에 woowacourse 레포지토리와 혹은 이 레포지토리의 다른 분들 PR을 참고하셔서 각 메서드들을 분리하시는 연습을 꼭 해보셨으면 좋겠어요 ㅎㅎ

자발적으로 발전을 위해 학습하시는 모습 너무 멋집니다! 잊으신 줄 알고 PR을 닫았는데, 잊지 않고 반영하시어 다시 PR을 보내주신 부분도 감명깊었어요 :)
앞으로 꽃길만 걸으시길 바라겠습니다!! 
ps) 질문등은 추가로 편하게 주셔도 좋아요!

2021-12-29 13:12 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +			} while (isAnswer == false);
ㅎ_ㅎ 취향차이 입니다~~! 부정연산자의 가독성이 떨어진다고 생각하는 동료들도 많습니다 
저도 두개이상의 조건에 부정연산자 들어가면 화딱지부터 나는 스타일이기도 하고요 ㅎ_ㅎ

전 false 직접비교보다는 isAnswer == false 같은 내용을 아예 메소드로 빼버릴 때도 많습니다 (그냥 부정연산자 쓸때도 있지만요!)
왜냐하면.. `==false`하면 인텔리제이가 부정연산자로 바꿀 수 있다고 노란줄 그어주는데.. 전 노란줄이 싫거덩여..
농담이고 좀 더 상황에 대한 설명을 가독성있게 해줄 수 있다는 측면(메소드 이름을 통해 표현할 수 있다)에서 이 방식을 선호합니다.

예시 ) 
```java
private boolean isNotAnswer(Param1 a, Param2 b){
    return !a.method(b);
} 

...
if( isNotAnswer(a,b) ) {
   // do Something
}
...
```

2021-12-29 13:12 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +	private final static String MESSAGE_NOTHING = "낫싱";
[구글에서 작성한 자바 컨벤션 가이드](https://google.github.io/styleguide/javaguide.html) 에선 다음과 같은 내용이 있는데요, 
`클래스 멤버의 제어자는 다음과 같은 순서로 작성한다`
> public protected private abstract default static final transient volatile synchronized native strictfp 

이 중 해당 멤버엔 private, static, final 제어자가 붙어있으므로 
비록 컴파일 에러는 없지만 `private static final` 순서로 작성해주는 것이 좋습니다 :)

2021-12-29 13:12 UTC, sihyung92 commented on src/main/java/baseball/Application.java
> +		TreeSet<Integer> inputNumberArray = new TreeSet<>();
자바의 컬렉션 프레임워크(List, Set, Map)은 인터페이스에 핵심기능을 잘 정의한 대표적인 사례입니다. 현재 TreeSet 구현체에 있는 기능을 활용하는 게 아니기 때문에 확장을 위해 인터페이스 타입으로 할당해주세요!
그리고 Array라는 이름은 해당 변수의 자료형을 배열이라고 의심하게 만드므로, Set으로 명시해주는 게 좋겠네요.
```suggestion
		Set<Integer> inputNumberSet = new TreeSet<>();
```

2021-12-29 13:12 UTC, sihyung92 commented on README.md
> ++ [x] 메소드에서 inputNumber를 받을 때 String 이 아니라 int로 받기(버그가능성)
String을 int타입으로 받음으로써 타입 안정성을 보장하는 경험을 하셨네요 💯 
하지만 int는 정수형임을 보장해 줄 뿐, -1 이라는 ballCount는 있을 수 없다는 내용까지는 포함할 수 없습니다. 이럴 때 BallCount 라는 객체를 만들고, 생성자에서 -1일 땐 예외를 던지도록 구현한다면 BallCount 객체를 인자로 받는 메서드는 BallCount가 -1이 아님을 확신하고 사용할 수 있겠죠 :)

2022-01-04 07:35 UTC, jiyoung-Heo commented
피드백 감사합니다 :)

피드백 주신 부분 모두 변경 완료했습니다.!
구현하다 보니 궁금한 부분이 생겼는데요, 

피드백 중에
'
1. inputNumber()쪽에서 입력받은 String이 '숫자모음인지' 에 대한 검증을 해주셨는데, compareNumber() 메소드에서 String으로 받으면 값에 대한 검증을 다시 한번 진행해야합니다.
2. int는 정수형임을 보장해 줄 뿐, -1 이라는 ballCount는 있을 수 없다는 내용까지는 포함할 수 없습니다.
'
라는 피드백을 주신적이 있었습니다. 

그렇다면 파라미터에 들어가는 모든 변수들을 검증을 해야하지 않을까...? 그렇다면 모든 메서드마다 검증을 해야하는것 아닌가..? 라는 생각이 들었습니다. 
어떤 기준? 으로 유효성체크를 해야 하는 것인지 궁금합니다!!

2022-01-05 11:40 UTC, sihyung92 commented
클래스 분리!! 멋집니당 ㅎㅎ 아마 처음 클래스를 분리할 때 어떻게 나누어야 할지 고민이 많으셨을텐데, `객체지향은 현실세계의 은유다`라는 표현이 도움이 될 것 같습니다. 
클래스는 객체의 틀입니다. 객체는 클래스를 new 함으로써 탄생하고, 더이상 쓰지 않으면 Garbage Collector에 의해 죽음을 맞습니다. 삶과 죽음이라는 비유에 빗대어, 객체가 살아있는 유기체라고 생각해주세요. Application이라는 객체가 동작하려면 그 안에서 BaseballGame이라는 객체가 필요하므로 탄생시킵니다. 
startGame()을 하라고 메시지를 전달해 일을 시키지만, 실제로는 재시작 | 중단도 해당 메서드 내에서 하고 있죠? 이게 어색하다고 느껴진다면, startGame()의 바깥 while문을 application으로 끌어올리고, 새로운 게임을 계속해서 만드는 방법도 있을 겁니다.

```java
public class Application {

    private static final String REQUEST_END_OR_RESTART = "게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요";
    private static final String COMMAND_RESTART_GAME = "1";
    private static final String COMMAND_END_GAME = "2";

    public static void main(String[] args) {
        do {
            BaseballGame baseballGame = new BaseballGame();
            baseballGame.startGame();
        } while (isNotStartOver(getInputStartOver()));
    }

    private static boolean isNotStartOver(String inputNumber) {
        if (inputNumber.equals(COMMAND_RESTART_GAME)) {
            return false;
        } else if (inputNumber.equals(COMMAND_END_GAME)) {
            return true;
        } else {
            throw new IllegalArgumentException();
        }
    }

    private static String getInputStartOver() {
        System.out.println(REQUEST_END_OR_RESTART);
        return Console.readLine();
    }
}
```
혹은 BaseBallGame이 start하고나면 중단과 재시작도 객체 내부에서 처리하는 게 **맞다고** 생각이 들면, 지금 구조대로 가도 될 것 이고요. 정답은 없되, 클래스명과 변수명, 메서드명을 통해 해당 코드가 논리적으로 설명되는가? 를 고려하시면 객체지향 초기에는 도움이 됩니다. 

잡설이 길었는데.. 질문에 답변하자면!
매우 좋은 질문이고요, 모든 메서드마다 검증을 해야하는 중복!! 때문에 비즈니스 로직을 하나로 묶어 class로 만듭니다. 현재 넘기고 있는 인자 int inputNumber를 대신해 클래스를 하나 만듭니다. Ball 하나하나를 대표할 클래스이니.. Ball이라고 할까요? 
```java
public class Ball {

    private static final int MINIMUN_NUMBER = 0;
    
    // 값이 불변하도록 
    private final int number;

    public Ball(int number) {
        numberValidate(number);
        this.number = number;
    }

    // 주생성자, 부생성자 패턴
    // 부생성자는 클라이언트 개발자가 사용하기 편하도록 많은 생성자를 제공한다
    public Ball(String number) {
        this(convertInteger(number));
    }

    private static int convertInteger(String number) {
        try {
            return Integer.parseInt(number);
        } catch (NumberFormatException e) {
            // 에러 되던지기
            throw new RuntimeException("입력된 number가 정수값이 아닙니다.", e);
        }
    }

    private void numberValidate(int number) {
        if (number < MINIMUN_NUMBER) {
            throw new RuntimeException(
                String.format("number가 최소 숫자보다 작습니다. 입력된 숫자 : %d, 최소 숫자 : %d", number,
                    MINIMUN_NUMBER));
        }
    }

    public int getNumber(){
        return number;
    }
}
``` 
짜다가 다시 보니 inputNumber는 숫자 한개를 상징하는게 아니라 3개 숫자 모두네요 ^^; 클래스 하나를 더 만들죠

```java
public class Balls {

    // 클라이언트가 0이 첫번째 공인지, 1이 첫번째 공인지 헷갈리지 않도록 상수화 해줍시다
    public enum BallIndex {
        FIRST(0),
        SECOND(1),
        THIRD(2);

        private final int index;
        
        BallIndex(int index) {
            this.index = index;
        }

        public int getIndex() {
            return index;
        }
    }

    private static final int BALLS_SIZE = 3;

    private final List<Ball> values;

    // new 를 통해 클래스를 만들지 못하도록 private 접근제어자를 활용합니다.
    private Balls(List<Ball> values) {
        this.values = values;
    }

    // 대신 제가 원하는 방법대로 클래스를 만들도록 강요하는 정적 팩토리 메서드를 제공합니다.
    public static Balls of(String numbers) {
        if (numbers.length() != BALLS_SIZE) {
            throw new IllegalArgumentException(String.format("숫자는 %d글자 여야 합니다.", BALLS_SIZE));
        }
        // 보통 스트림으로 처리하지만 이해를 돕기위해 for문으로 작성하였습니다
        List<String> ballNumbers = Arrays.asList(numbers.split(""));
        List<Ball> values = new ArrayList<>();
        for (String ballNumber : ballNumbers) {
            values.add(new Ball(ballNumber));
        }

        return new Balls(values);
    }

    //FIRST, SECOND, THIRD 중 하나로 공을 찾아갑니다.
    public Ball getFirstBall(BallIndex index) {
        return values.get(index.getIndex());
    }
}
```

이제 `String inputNumber` 인자들을 `Balls inputBalls`로 대체하여 사용하면 됩니다. 생성자에서 validation을 거치기 때문에, 객체가 오류없이 생성되었다면 해당 객체는 완전합니다.(불변식을 지켰다고 표현합니다.) 사용하는 입장에서는 이 String이 완전한 것일까? 하는 의심없이 코드를 작성할 수 있습니다. 

하나의 예시를 보여드린 것인데요, 그렇다면 모든 validation은 객체화해서 관리해주는게 좋을까요!? 하지만 우린 완벽하지 않기에, 모든걸 완벽하게 설계하려고 하면 프로그램을 작성하는데 오히려 방해가 됩니다. "먼저 동작하는 쓰레기를 만들어라" 라는 방침을 기억하시고, 다소 엉성한거 같더라도 동작하도록 만든 뒤에(객체화 없이 원시값으로 받아서 처리한 다음) 리팩토링을 통해 코드 퀄리티를 높여주세요. 

질문에 대한 답을 요약하면 `어떤 개념에 대한 유효성 검사가 반복되면 클래스로 만들어라` 가 되겠네요 ㅎ_ㅎ

2022-01-23 14:04 UTC, jiyoung-Heo commented
피드백 주신 부분 너무 늦게 확인했습니다 죄송합니다ㅜㅜ

저는 항상 validation을 통해서만 예외처리를 하도록 생각하고 있었는데 써주신 코드를 공부하다 보니
애초에 ball을 관리하는 클래스를 분리해서 사용하고, 생성자에서 예외처리를 하도록 하니까 중복된 검증도 할 필요가 없어지는것을 확인했습니다.

말씀대로 처음부터 이런식으로 생각해서 코드를 작성하려고 하면 보다 혼란스러워 질 수 있을것 같습니다. 물론 적응이 되거나 실력이 높아지면 바로 작성할 수 있겠지만 일단 제 실력에서는 돌아가는 코드로 작성하고 리팩토링 해보는 연습이 필요할 것 같다고 생각했습니다. 

감사합니다!!

2024-01-23 21:26 UTC, closed without merging