[숫자 야구 게임] 화난 라이언 미션 제출합니다.
REVENGE-WOOTECO/java-baseball-precourse pull request #3
Opened 2021-11-28 08:27 UTC by leejohy-0223

클래스마다 고유의 역할을 하도록 최대한 분리를 했는데 가독성이 더 떨어지는 거 같아 고민입니다 따끔한 충고 부탁드립니다.🤣

**배운 점**
- check style rule 활용
- Test code 작성 방법
- 깃은 좀 익숙치 않아서 마지막에 rebase 하는 과정에 fix commit이 추가되었습니다.

2021-11-28 18:21 UTC, lns13301 requested changes
안녕하세요. 화난 라이언님! 🦁
이번에 코드 리뷰를 하게된 우아한테크코스 3기 와일더라고 합니다. 🃏

생각 이상으로 구현을 잘해주셔서 놀랐어요!
이미 자바 코드를 어느정도 구현해보신 경험이 있으신거 같아요! 💯

예상한 것보다 좀 더 깊이있는 피드백을 드렸는데, 이해가 되지 않는 부분은 코멘트 남겨주세요! 😀

2021-11-28 18:21 UTC, lns13301 commented on README.md
> +## 🔧 야구게임 기능 요구 사항 정리
README 에 기능 구현에 대한 내용을 정리해주셨군요. 👍

살짝 아쉬운 점은 정리해주신 내용은 해당 README 파일에 이미 적혀있는 내용인데요, `docs/README.md` 경로에 따로 관리해보는건 어떨까요?

추가로 기능구현에 대한 내용을 세분화해보면 좋을 것 같아요. 😉
```
- 잘못된 값을 입력할 경우 IllegalArgumentException을 발생시킨다.
    - [x] 0 을 입력한다.
    - [ ] 입력 단위를 4자리를 입력한다.
```

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/Application.java
> +	public static void main(String[] args) {
Space 가 8칸으로 적용되었네요. 🤔
4칸으로 변경해주시면 좋겠어요. 😁

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/Constant.java
> +	public static final String REQUEST_INPUT_NUMBER = "숫자를 입력해주세요 : ";
매직넘버의 경우 다음과 같은 상황에서 사용한다고 생각해요.
1. 중복 사용
2. 상수를 보고 의미를 파악할 수 없을 경우

이런 메시지의 경우 중복 사용되고 있지않고, 의미를 파악할 수 있는 문장이라 상수로 관리하지 않아도 된다고 생각해요.
어떤 메시지를 사용해야하는지 상수를 체크해야하는 번거로움이 생길 수 있어서 이런 경우에 저는 상수를 사용하지 않아요. 이 부분은 개인마다 생각이 다른 부분이라 라이언님의 생각이 궁금하네요.

추가로 모든 상수를 따로 관리하면 어떤 이점이 있을까요?
한 클래스에서만 사용되는 상수의 경우 해당 상수가 어떤 의미인지 알기 위해 `Constant` 클래스를 찾아가려면 복잡해 보이는데, 이 부분에 대해 라이언님의 생각이 궁금하네요. 🤔

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/domain/Computer.java
> +	public boolean checkValue(String check) {
메서드 이름을 동사로 적다니 메서드네이밍에 대해서 잘 알고 계시군요! 👍

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/domain/Computer.java
> +	public static String getRandomValue() {
메서드 접두어로 get/set 을 사용하는 메서드의 경우, 속성(attribute)에 접근하는 메서드에 사용합니다.
```
public String getValue() {
    return value;
}
```

해당 메서드의 접두어를 변경해보는건 어떨까요? ☺️

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/domain/Computer.java
> +		StringBuilder sb = new StringBuilder();
String 대신 StringBuilder 를 사용했을 때, 어떤 이점이 있을까요? 🤔

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/domain/Computer.java
> +		while (sb.length() != MAX_BALL_COUNT) {
지금 단계에서 해드릴 리뷰는 아니라고 생각하지만, 라이언님이 워낙 구현을 잘해주셔서 추가적인 리뷰를 남겨드려요! 😂

현재 `Computer` 클래스는 숫자 3개의 야구게임만 진행가능해 보입니다.
만약 야구 게임 규칙이 변경되어서 4개의 숫자를 맞춰야 하는 상황이 발생했을 때, 어떻게 하면 `Computer` 클래스의 내부 구현을 변경하지 않고 숫자 4개로 게임을 진행할 수 있을지도 생각해보면 좋을 것 같아요. 😁

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/view/Validation.java
> +	public static void validateGameNumber(String userInput) {
검증 구현을 해주셨군요. 👍

2021-11-28 18:21 UTC, lns13301 commented on src/test/java/baseball/domain/ComputerTest.java
> +	void extractRandomValue() {
테스트까지 추가로 진행해주셨네요! 😎

그런데 정말 랜덤으로 숫자 1,000개(혹은 그 이상)를 생성해서 테스트가 통과하면 문제가 없는 코드일까요? 🤔

2021-11-28 18:21 UTC, lns13301 commented on src/test/java/baseball/domain/ComputerTest.java
> +		for (int i = 0; i < 1000; i++) {
```suggestion
		for (int i = 0; i < 1_000; i++) {
```
1,000 이상의 수는 이런식으로 가독성을 높일 수도 있답니다. 😉

2021-11-28 18:21 UTC, lns13301 commented on src/test/java/baseball/view/ValidationTest.java
> +	void exception_occur_in_validateGameNumber(String input) {
`Validation` 테스트도 잘해주셨어요! 👏👏

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/view/PrintView.java
> +			sb.append(ball).append(BALL).append(" ");
`" "` 이건 상수로 관리하지 않는 이유가 있을까요? 🤔

2021-11-28 18:21 UTC, lns13301 commented on src/main/java/baseball/domain/Computer.java
> +		PrintView.printResult(ball, strike);
이 부분은 MVC 관점에서 생각할 때, 문제가 될 수 있는 부분입니다. 당장 이해가 어렵다면 넘어가셔도 무방합니다. 😉
도메인 모델이 View 를 알면 어떤 문제가 있을까요? 🤔

2021-11-28 18:26 UTC, lns13301 requested changes
.

2021-11-30 12:15 UTC, leejohy-0223 commented on README.md
> +## 🔧 야구게임 기능 요구 사항 정리
네! 안그래도 거의 동일한 내용이라 필요성을 못느꼈는데, 세분화시켜서 관리해보겠습니다 😭

2021-11-30 12:20 UTC, leejohy-0223 commented on src/main/java/baseball/Constant.java
> +	public static final String REQUEST_INPUT_NUMBER = "숫자를 입력해주세요 : ";
매직 넘버에 대해서 너무 무분별하게 사용했다고 느꼈습니다!
IDE에서 바로가기를 통해 Constant로 이동이 가능하지만, 다시 생각하니 그 과정도 번거롭다는 생각이 드네요!

2021-11-30 12:22 UTC, leejohy-0223 commented on src/main/java/baseball/domain/Computer.java
> +	public static String getRandomValue() {
자칫 내부 프로퍼티에 대한 getter / setter로 오해할 수 있겠네요! 😭

2021-11-30 12:25 UTC, leejohy-0223 commented on src/main/java/baseball/domain/Computer.java
> +		StringBuilder sb = new StringBuilder();
StringBuilder의 경우 객체 수정이 가능해서, 불변인 String보다 메모리를 덜 사용할 수 있다 정도만 알고있었습니다!
더 공부해보겠습니다 😂

2021-11-30 12:50 UTC, leejohy-0223 commented on src/test/java/baseball/domain/ComputerTest.java
> +	void extractRandomValue() {
생각하기가 쉽지 않네요..!  구현 로직상으로는 이치에 맞지만 랜덤값 테스트는 어떻게 하는게 좋을까요?
또한 위의 테스트를 진행해보기 위해, Computer 내부에서만 사용되는 getRandomValue 메서드를 public으로 두고 진행했는데 이 부분도 어떻게 해야할 지 많이 고민을 했던 것 같습니다😭

2021-11-30 12:52 UTC, leejohy-0223 commented on src/main/java/baseball/view/PrintView.java
> +			sb.append(ball).append(BALL).append(" ");
"blank" 로 두는게 나을 것 같습니다!

2021-11-30 12:57 UTC, leejohy-0223 commented on src/main/java/baseball/domain/Computer.java
> +		PrintView.printResult(ball, strike);
View의 메서드가 변경될 경우 도메인 모델에도 적용해야 해서 변경에 취약해질것으로 생각이 됩니다😲
View를 인터페이스로 만들고 퍼블릭 메서드를 정의해서 구현하면 될까요..?

2021-11-30 13:11 UTC, leejohy-0223 commented on src/main/java/baseball/Application.java
> +	public static void main(String[] args) {
네이버 코드 컨벤션 적용해서 진행했는데, IntelliJ상에서는 문제 없는데 push 도중 문제가 생긴 듯 합니다 😂
잘못된 부분 확인하겠습니다.

2021-11-30 13:19 UTC, leejohy-0223 commented
바쁘신 와중에 코드리뷰를 경험해볼 수 있도록 도움주셔서 감사합니다👏
깃허브를 통해 처음으로 pull request 후 받아보는 리뷰인데, 너무도 배울점이 많고 스스로 알아가야할 부분이 많다는 것을 느꼈습니다!
말씀하신 부분 잘 보완해서 다음 미션 진행하도록 하겠습니다~~

2021-11-30 13:41 UTC, lns13301 commented on src/main/java/baseball/Constant.java
> +	public static final String REQUEST_INPUT_NUMBER = "숫자를 입력해주세요 : ";
사실 IDE 를 사용하면 찾아가는게 큰 문제가 되지 않지만, IDE 를 사용하지 않는 상황을 고려해볼 수 있을거 같아요! 😁

2021-11-30 13:46 UTC, lns13301 commented on src/main/java/baseball/domain/Computer.java
> +		StringBuilder sb = new StringBuilder();
StringBuilder 로 구현하셔서 인상적이었습니다. 그래서 바로 따봉을 드리려고 했지만, String 과 StringBuilder 의 차이점을 이해하고 사용하고 있는지를 확인하고 싶었습니다. 💯

2021-11-30 14:37 UTC, lns13301 commented on src/test/java/baseball/domain/ComputerTest.java
> +	void extractRandomValue() {
1. 랜덤 테스트
랜덤은 테스트하기가 굉장히 어려운 부분입니다. 저도 예전에 미션할 때 답답했었던 경험이 떠오르네요. 😂
이번 미션을 보면 우아한테크코스에서 RandomUtil 을 제공하고 있습니다. Random 에 대한 검증을 여기서 보장하겠다고 볼 수 있습니다.
그렇다면 테스트는 어떻게 구현하면 좋을까요?

한번 생각하는 시간을 가져보고 펼쳐보기를 눌러보세요.
<details>
<summary>펼쳐보기</summary>
<div markdown="1">
제 생각이 꼭 정답은 아닙니다.<br><br>
우선 <b>랜덤을 테스트하지마라</b>는 명심하시면 좋겠어요.

1. 파라미터를 주입하여 테스트하기
기본 제공되는 테스트를 보시면 파라미터로 테스트를 진행합니다. 예외가 발생하는 값, 통과하는 값으로요. 물론 이 값 이외의 값에서 예외가 발생하는 상황이 일어날 수도 있겠지만, 적어도 개발자가 예상한 값에 대해서는 통과된다는 보장이 됩니다. 하지만 랜덤 자체로 테스트를 진행하면 개발자가 예상못한 값에 대한 예외가 발생할 수 있겠죠.<br>
기능 자체를 검사하고 싶다면, 파라미터로 값을 받아서 기능이 동작하도록 구현하고, 파라미터는 랜덤 값을 주입하는 방법을 생각해볼 수 있습니다. 두 번째 예시를 보시죠.

2. 랜덤을 주입받는 메서드로 변경하기
메서드 내부에서는 원하는 기능을 동작하도록 구현하고, 랜덤을 주입받는 방법을 사용하는 것입니다.
아래 예시는 설명을 위해 코드를 변경한 부분이라 참고만 해주세요. 해당 기능에서 랜덤을 주입하는 예시는 좀 억지 느낌이 드네요.. 😂
```java
	public void resetValue() {
		value = "";
		
		while (value.length() != MAX_BALL_COUNT) {
			appendRandomValue(() -> Randoms.pickNumberInRange(MINIMUM_NUMBER, MAXIMUM_NUMBER));
		}
	}

	private void appendRandomValue(Supplier supplier) {
		String randomNumber = String.valueOf(supplier.get());

		if (!value.contains(randomNumber)) {
			value += randomNumber;
		}
	}
```

이 부분에 대해 좀 더 알아보고 싶으시면 <b>전략패턴</b>에 대해서도 알아보면 도움이 될거 같아요. 😁
</div>
</details>

2. 메서드 접근 제어자
테스트를 위해 메서드의 접근 제어자를 public 으로 두는 것은 좋지 못합니다. private 메서드를 사용하는 상위 public 메서드에서 테스트를 진행해도 충분하지 않을까요? [이글](https://justinchronicles.net/ko/2014/07/14/dont-do-testing-private-methods/)도 참고해보시면 좋을거 같아요. 😊

2021-11-30 14:40 UTC, lns13301 commented on src/main/java/baseball/domain/Computer.java
> +		PrintView.printResult(ball, strike);
지금 구현을 Computer 하나에서 하다보니 이런 상황이 발생했어요. 아마 다음주 미션부터 클래스 분리의 요구사항이 추가될거에요. 그에따라 Controller, Domain 을 분리하여 구현하게 된다면 Computer 에서 처리가 필요한 `기능`을 Domain 에 배치하시고, 전체적인 로직의 흐름, View 는 Controller 에서 처리하면 되겠습니다. 이번 미션은 이대로 두셔도 좋습니다. 💯

2021-11-30 14:53 UTC, lns13301 approved these changes
화난 라이언님 미션하느라 고생많았어요!
다음주 미션도 파이팅입니다!! 👍💯😉😁

2021-12-05 02:37 UTC, merged