[숫자 야구 게임] 노력 미션 제출합니다.
REVENGE-WOOTECO/java-baseball-precourse pull request #4
Opened 2021-11-28 10:58 UTC by yuminhwan

최대한 객체 지향적으로 구현하려고 했지만 각자 알맞은 역할과 책임을 가지고 있는 지 정확히 모르겠습니다. ㅠㅠ 
아직 공부를 많이 해야한다는 것을 느꼈습니다!
따끔한 충고 부탁드립니다!!

2021-11-28 11:50 UTC, xlffm3 requested changes
안녕하세요 yuminhwan님.
코드 잘 읽었습니다. 노력하신 흔적이 보이네요! 커멘트 드린 부분이 지금 당장은 적용하기 어려울 수 있는데요. 고민해보시고 적용하기 어려운 부분은 패스하고 피드백 반영해주세요~

아마 제가 드린 피드백을 제대로 적용하려면 프로젝트 구조를 조금 더 변경해야할텐데요.

현재 Domain 패키지 내부에는 비즈니스 로직과 입출력을 담당하는 View 로직이 산재되어있어요.
아무리 웹 어플리케이션이 아니더라도 콘솔 I/O는 View라고 생각해보시고,
현재 어플리케이션을 MVC 기반으로 변경해보세요. (다만 어렵다면 패스하셔도 됩니다)
Controller는 지금처럼 별도의 클래스를 두어도 되고, Application 클래스를 Controller라고 생각하시고 메인 메서드에 작성하셔도 됩니다.

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/GameController.java
> +	public static final String END_COMMAND = "2";
## Format 관련

Indent가 8 Space로 구성된것같아요. 일반적으로 4 Space를 쓰는데, IntelliJ IDE에서 설정하시면 됩니다.
Google Style을 적용하고 싶다면 https://jiyeonseo.github.io/2016/11/15/setting-java-google-style-to-intellij/ 글을 참고해주세요.

## 상수 관련

해당 클래스 내부에서 사용할 상수라면 public이 아닌 private으로 두는 것을 추천드려요. 클래스 내부 상태 변수, 상수 등을 외부로 노출시키면 어떤 점이 안 좋을까요?

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/GameController.java
> +	}
객체 사용에 필요한 변수를 자체적으로 내부에서 생성 중인데요.
컨트롤러라 크게 외부 주입이 필요하지 않더라도 외부에서 인자를 받아 주입하도록 코드를 작성하도록 노력해보세요.  A 객체가 B, C, D 객체를 의존할 때 외부에서 주입받는 방식과 내부에서 자체 생성하는 방식은 어떤 차이가 있고 외부 주입 방식에는 어떤 장점이 존재할지 고민해봐도 좋겠네요.

객체지향과 매우 밀접한 부분입니다 :)

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/GameController.java
> +}
파일 마지막에 NewLine을 넣어주세요. POSIX 표준입니다.
IntelliJ에서 마지막에 NewLine을 자동으로 삽입해주는 기능을 제공하고 있습니다.
https://xlffm3.github.io/ide/intellij_save_actions/

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/GameController.java
> +		} while ( !referee.isAnswer() );
```suggestion
		} while (!referee.isAnswer());
```

코드 전반적으로 공백과 관련된 컨벤션이 뒤죽박죽입니다!
자동으로 코드 컨벤션에 맞게 포맷팅해주는 기능을 IDE에서 제공 중이에요.

https://xlffm3.github.io/ide/intellij_save_actions/

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/Computer.java
> +	private BaseBallNumber computerNumber;
어떤 클래스는 final 변수를, 어떤 클래스는 가변을 사용하고 있어요.
어플리케이션 특성상 가변 객체를 사용할 수 밖에 없는 경우도 있겠지만, 현재 로직은 불변 객체를 선언해도 될 것 같습니다. 가급적 프리코스 미션할 때 불변 객체를 사용하는 방법에 대해 고민해보시면 좋을것같아요.

마찬가지로 변수를 외부에서 주입받는 방법에 대해 고민해보세요.

불변 객체의 장단점이 뭘까요?

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/Player.java
> +	}
Computer 클래스 리뷰와 동일합니다. 불변 객체를 선언해보고 주입받아보세요.

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +	}
일급 컬렉션의 사용과 생성자 주입 방식 좋습니다. 👍

* 다만 변수 타입을 ArrayList로 주는 이유가 있을까요? 상위 인터페이스를 사용할 때 장점이 뭔지 고민해봐요.
* 클래스명이나 변수명은 명확하게 해주는게 좋습니다. 지금은 baseballnumber의 컬렉션인데 클래스명이나 변수명은 은 단수네요. 복수로 작성해주세요.

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +		HashSet<Character> duplicateNumber = new HashSet<>();
HashSet 타입이 아닌 상위 인터페이스 타입을 사용하세요.

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +			}
```Character.isDigit()```과 같은 기본적으로 제공하는 API를 사용하면 코드가 더 직관적입니다.

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/Referee.java
> +
마찬가지로 가변객체를 사용하지 않고 작성해보는 연습을 해봅시다~

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/Referee.java
> +		}
depth를 1로 줄여보면 좋을것같아요.

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/Referee.java
> +	}
같은 BaseBallNumber 객체끼리 메시지를 주고받으며 스트라이크 여부를 판별하는데 상태를 getter로 외부에 노출하고 있습니다. 
객체끼리 메시지를 주고받도록 변경해보세요~

2021-11-28 11:50 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +	}
야구공 번호들의 컬렉션을 BaseballNumbers라는 클래스로 정의했다면,
각각의 야구공 번호 Integer 또한 BaseballNumber라는 객체로 정의하고, 여러 로직을 해당 부분에 위임할 수 있지 않을까요?

2021-11-28 11:51 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +	public int getNthNumber(int idx) {
Nth가 무슨 의미일가요?

2021-11-28 13:35 UTC, yuminhwan commented on src/main/java/baseball/GameController.java
> +	public static final String END_COMMAND = "2";
안녕하세요 xlffm3님.
바쁘실텐데 이렇게 좋은 리뷰 남겨주셔서 감사합니다!! 
하나하나씩 바꾸기 위해 먼저 Format설정을 바꾸려고 합니다. 
이미 사전에 말씀하신대로 요구사항에 나온 https://naver.github.io/hackday-conventions-java
해당 컨벤션을 IntelliJ IDE에 설정해놨습니다.
설정해놨지만 왜 저렇게 보일까 찾아보니 Code Style 설정에 Use tab character를 체크하면 이렇게 되더군요  
( 사진의 경우 테스트용으로 다른 파일을 사용했습니다. ) 

- 체크시 
<img width="815" alt="스크린샷 2021-11-28 오후 10 31 25" src="https://user-images.githubusercontent.com/65746780/143770051-566a8481-da24-4b2a-80f0-152b6a7a616a.png">

- 체크 해제시
<img width="787" alt="스크린샷 2021-11-28 오후 10 30 43" src="https://user-images.githubusercontent.com/65746780/143770046-141601ea-3b68-4c14-9234-e33bcf5c570d.png">

이런 경우 해제를 하는 것이 맞는것인가요?

2021-11-28 14:02 UTC, yuminhwan commented on src/main/java/baseball/GameController.java
> +		} while ( !referee.isAnswer() );
save actions의 경우 프로젝트마다 설정을 해줘야하나요?? 
다른 프로젝트로 들어가보니 체크가 다 해제되어 있네요 ㅎㅎ 
또한, 파일 저장이 맥북 기준 cmd + s를 뜻하는 게 맞을까요??
좋은 정보 감사합니다!!

2021-11-28 14:04 UTC, yuminhwan commented on src/main/java/baseball/GameController.java
> +}
말씀하신 링크대로 설정을 해보았습니다. 
이 설정의 경우 파일 마지막 부분에 빈줄이 있으면 적용이 완료된 것 일까요?

2021-11-28 14:24 UTC, yuminhwan commented on src/main/java/baseball/GameController.java
> +	public static final String END_COMMAND = "2";
클래스 내부 상태 변수, 상수 등을 외부로 노출시키면 
외부에서 변경될 가능성이 있기 때문에 안 좋을 것같습니다.

2021-11-28 16:25 UTC, yuminhwan commented on src/main/java/baseball/GameController.java
> +	}
```suggestion
	public GameController(Player player, Computer computer, Referee referee) {
		this.player = player;
		this.computer = computer;
		this.referee = referee;
	}
```

```
// Application.java
public class Application {
	public static void main(String[] args) {
		Player player = new Player();
		Computer computer = new Computer();
		Referee referee = new Referee();
		GameController baseBall = new GameController(player, computer, referee);
		baseBall.run();
	}
}
```

이런식으로 하면 외부에서 주입되는 것이 맞을까요?? 
외부에서 주입됨으로써 더욱 유연해져 변경에 용이할 듯 합니다!

2021-11-28 16:36 UTC, yuminhwan commented on src/main/java/baseball/domain/Referee.java
> +
computerNumber 와 strike, ball 모두 말씀이신가요?

2021-11-28 16:41 UTC, yuminhwan commented on src/main/java/baseball/domain/Referee.java
> +		}
for 안의 if 구문들을 한 메소드로 묶게 되면 depth가 1로 변경 되는게 맞나요? 
depth에 대한 정확한 이해를 못한것 같습니다.  ㅠㅠ

2021-11-28 16:57 UTC, yuminhwan commented on src/main/java/baseball/domain/Computer.java
> +	private BaseBallNumber computerNumber;
불변 객체로 생성 시 컴퓨터 객체를 게임 할때마다 생성하는 쪽으로 바꿔야 하는 건가요?

2021-11-29 12:21 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumber.java
> +	public int getNthNumber(int idx) {
조금 더 직관적으로 지을 수 있게 하겠습니다!!

2021-11-29 12:22 UTC, yuminhwan commented on src/main/java/baseball/domain/Referee.java
> +	}
최대한 getter을 안쓸려고 했지만 이부분에서 써버렸네요  ㅠㅠ 
BaseBallNumber 객체 안에서 getter을 쓰는 것은 객체끼리 메시지를 주고 받는다고 이해하면 될까요??

2021-11-29 12:22 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumber.java
> +			}
역시 함수를 쓰는 것이 더 직관적이군요 !! 감사합니다.

2021-11-29 12:35 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumber.java
> +		HashSet<Character> duplicateNumber = new HashSet<>();
상위 인터페이스 사용을 습관화 하겠습니다!!

2021-11-29 12:37 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumber.java
> +	}
상위 인터페이스를 씀으로써 더 유연해지겠네요!! 감사합니다. 
야구공 번호 자체를 객체로 만들 생각은 못했네요 !! 역할을 더욱 세분화 할 수 있군요!! 감사합니다.

2021-11-30 02:44 UTC, yuminhwan commented
안녕하세요 xlffm3님.
다시 한번 바쁘실텐데 이렇게 많은 리뷰를 남겨주신 점 감사드립니다!! 
리뷰 주신대로 리팩토링하면서 주입, 의존 등 많은 점을 배운 것 같습니다!! 
몇 가지 질문이 있습니다. 

## 1.  Formatter 관련 
이미 사전에 말씀하신대로 요구사항에 나온 https://naver.github.io/hackday-conventions-java
해당 컨벤션을 IntelliJ IDE에 설정해놨습니다.
설정해놨지만 왜 저렇게 보일까 찾아보니 Code Style 설정에 Use tab character를 체크하면 이렇게 되더군요.
이런 경우 어떤 것을 따라야 맞는 것인가요? 
- 체크시 
<img width="815" alt="143770051-566a8481-da24-4b2a-80f0-152b6a7a616a" src="https://user-images.githubusercontent.com/65746780/143974913-71fff836-d5d2-46d0-a940-977bc925e04d.png">

- 체크 해제시 
<img width="787" alt="143770046-141601ea-3b68-4c14-9234-e33bcf5c570d" src="https://user-images.githubusercontent.com/65746780/143974905-77578240-81a2-41bb-a033-3f5541f3090a.png">

<br> 

## 2. 상위 인터페이스 관련 
BaseBallNumbers클래스의 ArrayList를 List 로 변경하였습니다.
그런데 BaseBallNumbers 객체를 생성할 때 모두 ArrayList로 주입하는 쪽으로 구현하였는 데 
ArrayList보단 List로 주입하는 것이 맞을까요?

 <br> 

## 3. depth 관련
말씀하신 대로 depth를 줄이기 위해 메소드로 추출하여 사용하였는 데 이런 경우 depth가 1로 줄어드는 것이 맞을까요?
또한, 메소드로 추출하기 위해 Map객체를 사용하였는 데 depth 2로 구현하게 되면 변수만으로도 구현이 가능합니다.
이런 경우에도 depth를 줄이는 방법이 맞을까요?
<br> 
 
## 4. View 관련 
InputView의 경우 입력받고 그 값을 반환해주는 형식으로 구현해주었습니다. 
이 부분에 입력받은 값에 대한 유효성 검사를 해도 될까요? View부분에 로직을 구현해도 되는 지 여쭤보고 싶습니다. 
가능하다면 BaseBallNumbers객체에 원하는 값만 전달해줄 수 있을 것 같습니다.

질문이 많아서 죄송합니다😂
재리뷰를 신청해놨는데 보실지는 모르겠네요 ㅎㅎ 편하신 시간대에 의견주시면 감사하겠습니다!!
마지막으로, 다시 한번 감사드립니다!!

2021-11-30 07:12 UTC, xlffm3 approved these changes
안녕하세요 노력님.
사실 처음 과제 제출하실 때 이미 객체지향을 많이 학습하시고 기능을 구현한 느낌을 받아서
조금 더 어려운 난이도로 피드백을 드렸는데 정말 잘 구현해주셨어요. (MVC 등등...)

---

## 질문에 대한 답변

1. 일반적으로 체크 해제시의 것이 보편적인 코드 컨벤션입니다.
2. 약간 이 부분은 추가적인 학습이 필요해보여요. 현재 모든 주입을 ArrayList로 하고 있습니다. 다만 이를 사용할 변수의 '타입'이 List 인터페이스냐 ArrayList냐의 차이입니다. 상위 인터페이스를 사용하면 뭐가 장점일까요? 구현체의 변경이 용이해집니다. 만약 코드를 추후에 LinkedList 등 다른 것으로 변경하고 싶다면 ArrayList 타입 변수를 사용 중인 코드는 모두 변경이 발생합니다.
3. 네, 조건문이나 반복문 블럭을 1 depth라고 봅니다. 실제로 하나의 depth로 모든걸 처리하기 어렵지만 클린코드 차원에서 해보는것을 추천드려요.
4. 이 부분은 스타일 차이이긴 한데요. View에서도 입력 유효성 검사를 진행해주는게 좋다고 생각합니다.

현재 대부분의 정적 팩토리 메서드들이 String만을 받고, 도메인 내부에서 String을 파싱해 유효성을 체크하고 객체를 검증하는 형태인데요.
String에 대한 입력값 검증은 View에서 하고, 값을 변환해주면 모델 단에서 데이터를 바탕으로 객체를 생성하는 방식이 있겠네요.

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/View/InputView.java
> +public class InputView {
MVC 기반으로 잘 분리해주셨네요 👍👍
만약 생성자가 필요없는 유틸성 클래스라면 메서드를 static으로 선언하고 private 생성자를 만들어도 괜찮습니다.

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +    }
논리정 동등성을 위해 equals를 재정의할때는 hashCode도 재정의하는 것이 좋습니다.
구글 검색해보시면 effective java 관련 글이 많이 나올거에요.

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumbers.java
> +            }
반복문 안에 if 조건이 있어서 depth가 2네요.
현실적으로 개발하다 보면 항상 지키기 어려운건 맞지만, 연습 차원에서 메서드를 분리해봅시다~

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/domain/Computer.java
> +    }
Computer가 사용할 BaseBallNumbers 또한 외부에서 주입받는것이 어떨까요?
지금 당장은 필요성을 못느끼더라도 나중에 테스트 코드를 작성하는 때가 된다면, 주입 방식이 아닐 때 테스트하기 어렵습니다.

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/message/SystemMessage.java
> +    public static final String INVALID_COMMAND_NUMBER = "1 또는 2만 입력해야 합니다.";
이 친구들은 View에서만 사용할거면 별도 상수로 추출하지 말고, View 내부 상수로 변경해도 좋겠습니다 :)

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/Application.java
> +        InputView inputView = new InputView();
MVC 잘 해주셨네요!
만약 현재 Application이 Controller라면 이러한 View 또한 생성자 주입을 받아 사용하면 Controller에 대한 테스트도 다양하게 진행할 수 있을 거에요.
또, View를 어느 시점에서는 콘솔 기반에서 웹이나 파일로 변경하더라도 Model 쪽에는 영향이 없겠죠 :)

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +    }
거의 대부분의 클래스들이 정적 팩토리 메서드를 가지고 있는데요.
생성자 인자가 1개밖에 없는 간단한 경우에도 정적 팩터리 메서드를 사용하는 이유가 있을까요?
정적팩토리메서드만 사용할것을 강제한다면 안 쓰는 public 생성자는 private으로 닫아주세요.

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumber.java
> +        }
상수 처리 및 꼼꼼한 예외처리 좋습니다.

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumbers.java
> +    public BaseBallNumbers(List<BaseBallNumber> baseballNumbers) {
만약 외부에서 해당 생성자를 사용하지 않을 예정이라면 private으로 변경해주세요.
외부에서의 불필요한 접근을 최소화하는 것이 좋습니다 :)

2021-11-30 07:12 UTC, xlffm3 commented on src/main/java/baseball/domain/Referee.java
> +    }
Referee가 BaseballNumbers로부터 사이즈를 요청하고 인덱스를 순회하며 결과를 담는 방식이네요.

제가 정답은 아니지만, Referee는 두 BaseballNumbers 객체를 가지고 있으니 이들끼리 메시지를 주고 받아서 바로 strikeCounts와 ballCounts를 계산해서 Referee에게 줄수도 있다고 봐요. (결국 위 로직이 Referee에 있느냐, 내부 정보에 더 가 까운 BaseballNumbers에 있느냐 차이이긴합니다.)

정답은 없습니다 ㅎㅎ 어떻게 생각하시나요?

2021-11-30 16:10 UTC, yuminhwan commented on src/main/java/baseball/View/InputView.java
> +public class InputView {
OutPutView처럼 구현하는 것이 좋겠군요!! 
private를 생성자로 쓸 필요가 있을까 했는데 public으로 하게 되면 객체를 생성할 수 있게 되니 안 좋을 것 같네요 ㅎㅎ

2021-11-30 16:11 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumber.java
> +    }
hashCode에 대해서는 생각도 못했는 데 배워갑니다 ㅎㅎ

2021-11-30 16:11 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumbers.java
> +            }
depth 줄이기에 더욱 집중해봐야겠습니다 ㅠㅠ

2021-11-30 16:12 UTC, yuminhwan commented on src/main/java/baseball/domain/Computer.java
> +    }
주입하는 방식으로 최대한 구현하도록 하겠습니다!!

2021-11-30 16:13 UTC, yuminhwan commented on src/main/java/baseball/message/SystemMessage.java
> +    public static final String INVALID_COMMAND_NUMBER = "1 또는 2만 입력해야 합니다.";
에러 메시지들도 다른 곳으로 옮기는 게 좋겠군요!! 감사합니다!

2021-11-30 16:17 UTC, yuminhwan commented on src/main/java/baseball/Application.java
> +        InputView inputView = new InputView();
현재 InputView를 유틸성 클래스라고 생각하면 지금 단계에선 주입을 한다는 것에 생각을 안해도 될까요? 
아님 InputView를 유틸성 클래스로 사용하지 말고 주입하는 방식이 맞을까요?? 헷갈리네요 ㅎㅎ

2021-11-30 16:21 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumber.java
> +    }
BaseBallNumbers 쪽에서 사용해야 하기 때문에 정적 팩토리 메소드를 사용했습니다. 
이런 경우에도 생성자를 사용해야 할까요?
private로 닫는 것은 생각도 못했네요! 감사합니다!!

2021-11-30 16:21 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumber.java
> +        }
감사합니다!!

2021-11-30 16:22 UTC, yuminhwan commented on src/main/java/baseball/domain/BaseBallNumbers.java
> +    public BaseBallNumbers(List<BaseBallNumber> baseballNumbers) {
접근에 대해 다시 한번 생각하게 된 것 같습니다. 
감사합니다!

2021-11-30 16:27 UTC, yuminhwan commented on src/main/java/baseball/domain/Referee.java
> +    }
Referee의 책임이 스트라이크인지 볼인지 체크해주는 것으로 생각했는 데 
현재 코드에서는 객체끼리 주고 받아서 계산한 뒤 Referee가 결과값을 저장해주는 형태로 하는 것이 더욱 깔끔할 것 같습니다.

2021-12-01 09:46 UTC, yuminhwan commented
안녕하세요 xlffm3님.
재리뷰를 했음에도 다시 한번 꼼꼼히 리뷰를 남겨주신 점 감사드립니다. 😂
말씀하신 대로 수정을 해보았는 데 염치없지만 몇가지 더 질문하려고 합니다 😓

<br>

## 1. InputView 관련 
- 현재 InputView에서 입력값을 받아 유효성 검사를 한 뒤 List<Integer>형으로 반환해주고 있습니다 
    - 하지만 현재 상태에서 BaseBallNumber가 1~9사이의 숫자인지도 중복으로 체크하고 있습니다. 
    - 이런 경우 InputView에서는 숫자인지만 판별하고 BaseBallNumber에서는 0인지만 체크하는 것이 더욱 옳바른 방법일까요? 
- 현재 InputView를 유틸성 클래스라고 생각하면 말씀하신 주입에 대해 크게 생각하지 않아도 될까요? ( 현재 구조에서 입니다 ! )

<br>

## 2. 상위 인터페이스 관련 
- 말씀하신 대로 List로 주입받도록 수정하였습니다. 
- 현재 상태에서 LinkedList로 바꾸려면 List로 주입한 코드를 모두 변경해야 하는 데 이런 경우 상위 인터페이스의 장점을 사용 못했다고 할 수 있나요? 

<br>

## 3. DTO 관련 
- 아직 공부가 많이 필요하지만 DTO를 통해 수정해보았습니다. 
- 현재 상태에서 DTO가 도메인에 의존하고 있는 데 이 경우는 괜찮은 건가요? 
- 또한, OutputView가 DTO에 의존하고 있는 데 괜찮은 건가요? 
- InputView와 마찬가지로 OutputView가 로직을 가지고 있는 데 이 경우 출력에 대한 로직이니 괜찮을까요??

<br>

리뷰를 받으면서 제가 어떤 것을 더욱 공부해야 하고 코드를 구현할 때 어떤 점을 생각해야 하는 지 방향성을 맞출 수 있었습니다. 
시간도 없으신 데 제가 귀찮게 한 건 아닌가 모르겠네요 ㅠㅠ 
방향성을 잡게 해주신 xlffm3님에게 감사드립니다!!!!

2021-12-08 09:57 UTC, xlffm3 approved these changes
안녕하세요, @yuminhwan  님!
리뷰가 늦어서 죄송합니다.  최근 면접이라 너무 바빴네요!

리뷰 반영 너무 잘해주셨습니다. 질문에 대한 답변은 전부 남겨두었으니 궁금하시면 연락이나 커멘트로 태그 해주세요~
pr merge하겠습니다.

2021-12-08 09:57 UTC, xlffm3 commented on src/main/java/baseball/view/InputView.java
> +    }
Q1. InputView 관련

* 네, 유틸성 클래스라면 생성자를 private으로 막아두고 사용하셔도 됩니다.
* 생성자가 없을 때 유틸클래스로 사용할지, 아니면 기본 생성자가 있는 객체로 사용할지는 상황에 따라 적절히 판단하시면 됩니다.

2021-12-08 09:57 UTC, xlffm3 commented on src/main/java/baseball/view/InputView.java
> +            .collect(Collectors.toList());
stream api 👍👍

2021-12-08 09:57 UTC, xlffm3 commented on src/main/java/baseball/view/InputView.java
> +    }
도메인 로직에서 이런 검사를 하는데 view에서도 입력값 유효성 검사를 하는게 맞는가 하는 질문이시죠?
이건 솔직히 작성자 마음이겠지만, 꼼꼼하게 해준다면 view도 유효성 검사를 진행해주는게 맞죠~

웹 페이지에서 회원가입할 때 아이디 비밀번호를 입력하면 '비밀번호는 특수문자와대문자를 포함해야합니다.'와 같은 문구를 보신적 있으실거에요~

웹 페이지(view)도 입력값을 검사하고, 뒷단 백엔드 도메인에서도 검사를 할 거랍니다. ㅎㅎ 
view에서 입력값 검증한다고 뒷단 백엔드 도메인에서 유효성 검사를 안 하면 어떻게 될까요??!

https://jojoldu.tistory.com/157

2021-12-08 09:57 UTC, xlffm3 commented on src/main/java/baseball/domain/BaseBallNumbers.java
> +    }
Q2. 현재 상태에서 LinkedList로 바꾸려면 List로 주입한 코드를 모두 변경해야 하는 데 이런 경우 상위 인터페이스의 장점을 사용 못했다고 할 수 있나요?

```java
public static void main(String[] args) {
   BaseballNumbers baseballNumbers = new BaseballNumbers(new ArrayList<>());
   baseballNumbers.play();
}
```

```java
public static void main(String[] args) {
   BaseballNumbers baseballNumbers = new BaseballNumbers(new LinkedList<>());
   baseballNumbers.play();
}
```

아닙니다. 지금 잘 사용하고 있습니다. 내부 필드가 List 타입인 만큼 어떤 구현체가 들어오든 내부 동작은 변함이 없어집니다. (OCP에 대해 학습해보시면 좋겠네요!)

다만 제일 외부에서 주입해주는 엔트리 포인트에서는 결국 코드가 변경될 수 밖에 없습니다.

2021-12-08 09:57 UTC, xlffm3 commented on src/main/java/baseball/dto/OutputDto.java
> +    }
Q3. 현재 상태에서 DTO가 도메인에 의존하고 있는 데 이 경우는 괜찮은 건가요?
Q4. 또한, OutputView가 DTO에 의존하고 있는 데 괜찮은 건가요?
Q5. InputView와 마찬가지로 OutputView가 로직을 가지고 있는 데 이 경우 출력에 대한 로직이니 괜찮을까요??

A3 : 도메인이 DTO를 의존하는것보다, DTO가 도메인을 의존하는 것이 낫습니다. 어차피 DTO 자체가 특정 도메인의 정보를 전달하기 위함이라 논리적으로 강하게 결합된 상태이기 때문입니다. 반대로 도메인이 DTO를 의존하면, (예를 들어 GameResult.toDto()) View 로직이 변경될 때 도메인이 변경되는 문제가 존재합니다.

A4 : DTO는 레이어간 데이터 전송 객체인만큼 OutputView는 알고 있어도됩니다.

A5 : 예, 뷰를 위한 로직도 있는게 정상입니다. 😇😇

---

단, Dto 네이밍은 OutputDto보다는 GameResultDto 등으로 정확히 명시해주는게 더 좋아보입니다!

2021-12-08 09:59 UTC, merged

2021-12-12 12:17 UTC, yuminhwan commented
안녕하세요 @xlffm3 님 
감사하다는 말 드리고 싶어서 이렇게 코멘트 남깁니다. 
그동안 꼼꼼하게 코드리뷰 주신 것 감사드립니다. 
코드리뷰를 받으면서 몰랐던 점과 체크해야할 부분 등 여러가지로 많이 배워가는 것 같습니다. 
면접때문에 시간도 없으셨을 텐데 마지막까지 이렇게 코드리뷰 남겨주신 점 감사드립니다!! 
면접 꼭 붙으셨으면 좋겠습니다!!
수고하셨습니다!!