[숫자 야구 게임] 정열맨 미션 제출합니다.
REVENGE-WOOTECO/java-baseball-precourse pull request #5
Opened 2021-11-29 11:46 UTC by highright96

고민하는 시간이 생각보다 길어져서 늦게 제출한 점 죄송합니다.
미션을 진행하면서 여러모로 많이 부족하다고 느끼는 것 같네요 😪
조언 부탁드립니다. 🙏

2021-11-30 12:47 UTC, Be-poz reviewed
정열맨님 안녕하세요!  
코드 잘 읽어봤습니다. 너무 잘 짜셨는데요?? 크게 제가 터치할 부분은 없는 것 같습니다. 코멘트에는 남기지 않았지만, if, elif, else 에 대해서는 else를 지양하는 방식을 사용하시면 좋을 것 같습니다.  

일부 작은 코멘트를 남겼습니다. 확인해주시면 감사하겠습니다.  
코드가 이미 좋다고 느껴져서 많은 리뷰를 남기지는 못했습니다!!

2021-11-30 12:47 UTC, Be-poz commented on src/main/java/baseball/domain/CommandType.java
> +            .filter(v -> v.getCode().equals(command))
``code`` 필드로의 직접 접근이 아니라 ``getCode()`` 를 이용해서 접근을 하신 이유가 있을까요? ?

2021-11-30 12:47 UTC, Be-poz commented on src/main/java/baseball/domain/Number.java
> +        this.numbers = numbers;
Number 생성자를 호출하는 곳에서 파라미터인 numbers에 값이 추가되거나 변경된다면 Number의 numbers의 내부 요소들은 영향을 받을까요 받지않을까요?  

List 자체에 대한 할당의 불변을 의도한 것이라면 지금 이대로도 좋은 것 같고, 내부 값에 대한 불변 또한 유지하고 싶다면 연결고리를 끊어내야 할 것 같습니다.

2021-11-30 12:47 UTC, Be-poz commented on src/main/java/baseball/domain/Number.java
> +    public boolean containsNumber(int number) {
``hasNumber``와 ``containsNumber``는 비슷하기에 혼동의 요지가 있는 네이밍 같습니다.  
조금 더 기능에 맞는 네이밍을 하면 좋을 것 같아요!

2021-12-01 00:25 UTC, sihyung92 requested changes
정열맨님 안녕하세요 웨지 입니닷~~  벌써 숙련자의 향이 솔솔 ㅎ_ㅎ 코드 잘 봤습니다~~ 두개의 피드백 남겼어요~~

2021-12-01 00:25 UTC, sihyung92 commented on src/main/java/baseball/domain/Hint.java
> +        if (strikeCount == ZERO && ballCount == ZERO) {
Hint 객체는 스트라이크 여부를 확인해주는 역할을 하고, 
해당 힌트를 기반으로 문자열을 만들어주는 역할은 다른 객체로 분리해도 좋을 것같아요 ㅎ_ㅎ
'표현식을 바꾸어야 한다', 'ball이나 strike를 계산하는 로직을 바꾸어야한다' 두가지 책임의 변경 여파를 하나의 클래스가 감당하므로 SOLID 원칙 중 SRP에 위배됩니다. (* 위배 되어도 됩니다! 규칙은 절대적인 것이 아니고, 내게 필요한 만큼만 적용하여 생산성을 끌어올리는 것 도 중요합니다. 하지만 인식하고 있는 건 중요하겟죠 ㅎ_ㅎ)

커맨드 타입을 이넘으로 분리하셨듯 이 부분도 이넘 객체를 만들어 처리할 수 있곘네요~?

2021-12-01 00:25 UTC, sihyung92 commented on README.md
> +## 구현 기능 목록
커밋 내역을 보니 docs를 마지막에 작성하셨네요 :) 
리드미는 도메인에 대한 개념을 정의하고, 어떤 기능을 작성할지 위한 목적으로 작성합니다. 최종적으론 타 개발자(이 타 개발자엔 미래의 나도 해당됩니다. 저희 기억력은 매우 한정적이니까요ㅎ_ㅎ)를 위한 문서가 되는 것이 목적이지만, 다음 번엔 시작단계에서 리드미를 작성하시는 연습도 해보시면 좋을 것 같아요!

리드미 작성 시 이점과 꿀팁은 다른 분 리뷰에 남긴 내용을 링크해 드릴게요
https://github.com/REVENGE-WOOTECO/java-baseball-precourse/pull/2#discussion_r757955685

2021-12-01 03:40 UTC, highright96 commented
Be-poz님 웨지님 바쁘신 도중에 제 코드를 봐주셔서 정말 감사합니다.  🙏
내일 이내로 남겨주신 피드백 반영하도록 노력하겠습니다.

2021-12-02 05:11 UTC, highright96 commented on src/main/java/baseball/domain/CommandType.java
> +            .filter(v -> v.getCode().equals(command))
습관적으로 `Getter`를 쓴 것 같습니다. 필드로 직접 접근하도록 변경했습니다!

2021-12-02 05:22 UTC, highright96 commented on src/main/java/baseball/domain/Number.java
> +        this.numbers = numbers;
List 자체에 대한 할당의 불변을 의도한 것이긴 하지만 내부 값에 대한 불변도 유지하는 것이 좋을 것 같습니다.

Number 클래스의 외부/내부에서 `numbers`의 내부 값을 수정할 수 없도록 생성자에서 불변 객체로 변환시켰습니다.

```java
  private Number(List<Integer> numbers) {
      this.numbers = Collections.unmodifiableList(numbers);
  }
```

2021-12-02 05:37 UTC, highright96 commented on src/main/java/baseball/domain/Number.java
> +    public boolean containsNumber(int number) {
코드를 짜는 것보다 메소드명을 짓는게 더 오래 걸리는 것 같네요😂

`hasNumber(int number, int idx)` -> `hasNumberInNumbersIndex(int number, int idx)`
`containsNumber(int number)` -> `containsNumberInNumbersRange(int number)`

메소드명을 변경해보았습니다!

2021-12-02 06:31 UTC, highright96 commented on src/main/java/baseball/domain/Hint.java
> +        if (strikeCount == ZERO && ballCount == ZERO) {
@sihyung92 
`Hint` 객체에서 메시지를 생성하는 역할을 `HintMessage`로 변경했습니다!
HintMessage를 이넘으로 분리하는 부분은 좀 더 고민이 필요할 것 같습니다 ㅠ_ㅠ

@Be-poz 
말씀하신 `if`, `elif`, `else` 방식을 좀 더 읽기 쉽게 바꿔봤습니다!

```java
public class HintMessage {

    private final static int ZERO = 0;

    private final static String STRIKE = "스트라이크";
    private final static String BALL = "볼";
    private final static String NOTHING = "낫싱";

    public static String toMessage(Hint hint) {
        if (hint.getStrikeCount() == ZERO && hint.getBallCount() == ZERO) {
            return NOTHING;
        }

        if (hint.getBallCount() > ZERO && hint.getStrikeCount() == ZERO) {
            return String.format("%d%s", hint.getBallCount(), BALL);
        }

        if (hint.getStrikeCount() > ZERO && hint.getBallCount() == ZERO) {
            return String.format("%d%s", hint.getStrikeCount(), STRIKE);
        }

        return String.format("%d%s %d%s", hint.getBallCount(), BALL, hint.getStrikeCount(), STRIKE);
    }
}
```

2021-12-02 06:37 UTC, highright96 commented on README.md
> +## 구현 기능 목록
요구 기능 목록을 먼저 작성했는데 깃헙에서 오류가 난걸까요? 😢

살아있는 문서를 만들기 위한 꿀팁!! 감사합니다. 👍

![image](https://user-images.githubusercontent.com/55661631/144370141-253c1d39-6085-48ab-8117-4c7779f0edcc.png)

2021-12-02 07:46 UTC, Be-poz commented on src/main/java/baseball/domain/Number.java
> +    public boolean containsNumber(int number) {
맞아요 항상 네이밍이 골치인 것 같아요!! ㅋㅋㅋ

2021-12-02 07:52 UTC, Be-poz commented
정열맨님 변경 내역 잘 확인했습니다! 처음부터 이미 너무 잘해주셔서 큰 피드백을 못해드려서 괜히 죄송하네유 ㅜㅜ 이만 머지시키겠습니다~

2021-12-02 07:53 UTC, Be-poz approved these changes

2021-12-02 07:53 UTC, merged

2021-12-02 08:33 UTC, highright96 commented
Be-poz님 고생 많으셨습니다. 감사합니다!! 👍👍👍