[숫자 야구 게임] 오리 미션 제출합니다.
REVENGE-WOOTECO/java-baseball-precourse pull request #6
Opened 2021-11-30 14:49 UTC by bbeomgeun

이번 주에 기말고사와 과제, 인턴 업무가 겹쳐서 너무 늦게 시작했습니다..
자바 언어를 이용해서 객체지향적으로 설계를 해본 적이 처음이라 많이 늦었습니다. 죄송합니다 ㅠㅠ

늦었지만 리뷰가 가능하다면 감사히 받겠습니다! 불가능해도 다른 분들 코드 리뷰 보면서 공부하겠습니다!!

3주차까지 열심히 따라가보겠습니다. 항상 감사드립니다.

2021-12-02 04:50 UTC, sihyung92 requested changes
구현 잘 해주셨네요 👏👏 꼼꼼한 리드미와 테스트작성까지 진행해주신 부분이 인상 깊었어요. 리뷰 남겼으니 확인해주셔요!

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/Validation.java
> +        return false;
좀 더 간결하게 표현할 수 있을 것 같아요 :) 라인 수를 줄이는 것이 절대적인 미덕은 아니지만, 조금 더 간결하게 표현할 수 있다면 가독성이 향상하기 때문에 염두에 두면서 코딩하는 것이 좋다고 생각합니다

```suggestion
        for (char c : input.toCharArray()) {
                duplicateCheck.add(c);
        }
        return duplicateCheck.size() != input.length();
```

혹은 스트림에 대해서 학습해보시면, 더 간결하고 명시적으로 표현할 수 있습니다~~!
```suggestion
        long count = input.chars()
            .distinct()
            .count();

        return count != input.length();
```

2021-12-02 04:50 UTC, sihyung92 commented on README.md
> +## 구현할 기능 목록
꼼꼼한 리드미 작성 좋아용 :)

2021-12-02 04:50 UTC, sihyung92 commented on README.md
> +## 구현할 기능 목록
커밋을 확인해보니 첫 커밋에 모든 요구사항을 작성해주셨더라구용! 멋집니닷 👍 
모든 요구사항을 떠올릴 수 있다면 그것도 좋지만, 좀 더 복잡한 요구사항이 되면 놓치는 부분도 생길거에요 ㅎ_ㅎ 그럴 때를 대비한 꿀팁도 링킹해드릴게요

https://github.com/REVENGE-WOOTECO/java-baseball-precourse/pull/2/files#r757957109

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/utils/Constant.java
> +public class Constant {
모든 상수를 모아놓은 클래스는 중복은 줄어들지만 결합도가 높아집니다. 

결합도는 객체지향에서 한 객체가 얼마나 많은 객체를 알고 있는가? 에 관한 내용이에요. 객체지향은 낮은 결합도를 추구합니다. 왜냐하면 결합도가 높으면, 이 객체가 변경되었을 때 함께 영향을 받는 클래스가 많아져 유지보수성이 낮아져서요 :) 

중복의 제거는 프로그래머가 반드시 갖춰야할 덕목이지만 이 정도의 상수들은 사용하고 있는 클래스에서 각자 정의해주어도 괜찮다고 생각해요. 객체지향은 '역할을 수행하는 책임을 가진 객체'가 '필요한 데이터를 직접 가지고 있는 것'을 추구합니다. 관련 내용은 조영호님이 쓰신 '객체지향의 사실과 오해'(토끼책)을 읽어보셔도 좋고 가볍게는 util클래스 에 대해 구글에 검색해보시면 다양한 논의가 있습니닷 ㅎ_ㅎ

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/Validation.java
> +public class Validation {
이 객체는 상태(필드, 멤버)는 없고 행위(메소드)만 있는데 굳이 인스턴스로 사용할 필요가 있을까요?? 🙂 달리 말하면 동일한 요청에 대해선 항상 동일한 응답을 반환하는데요, 모든 메소드를 static으로 사용하는 건 어떨까요?

모든 클래스가 static인 클래스를 util 클래스라고 부르는데요, 그렇다면 util 클래스는 사용하는 것은 좋은 방식일까요? 😗

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
validation을 요청이 들어오는 곳에서만 해주고 있네요 :) 검증 로직은 어느 곳에 위치하는 것이 좋을까요? 
지금처럼 유저의 입력이 직접 들어오는 부분? 아니면 다른 어딘가!?

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
IllegalArgumentException은 throws 표기해 줄 필요가 없습니다. 왜 그럴까요~~?? 
keyword는 runtime exception / checked exception, unchecked exception입니다 :)

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/MessagePrint.java
> +    public void getResultMessage(int strikeCount, int ballCount) {
MessagePrint라는 객체가 로직이 strike인지 ball인지 판단하고 있네요. 그 결과로 if else블록이 늘어나게 되었구요 :) MessagePrint는 순수하게 출력에만 집중하는건 어떨까요? 각 if블록을 메서드로 분리하고, 결과를 알고있는 객체가 상황에 따라 알맞은 메소드를 호출하도록 하면 될것 같네요!

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/GameManager.java
> +    String answer;
answer 같은 경우 run 메소드 내에서만 활용하도록(지역변수로) 리팩토링 할 수 있을 것 같네요! 두 개의 main문이 동일한 참조를 가진 GameManager의 run을 동시에 호출한다면, 오류가 발생할 것 같습니다.

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/GameManager.java
> +    NumberGenerator numberGenerator = new NumberGenerator();
전체 코드에서 접근제어자가 없는데, 그러면 default 접근제어자가 자동으로 붙습니다. public, default, private, protected 접근제어자는 어떤 차이가 있을지 찾아보시면 좋겠네요 :)

---

기본적으로 private 접근제어자를 붙이는 걸 권장드립니다. 이것은 객체지향에서 말하는 캡슐화와 관련이 있는데요, 
왜 멤버변수를 캡슐화 해야하는지 에 대해선 '객체지향의 사실과 오해'를 참고해보시면 좋을 것 같아용!

2021-12-02 04:50 UTC, sihyung92 commented on src/main/java/baseball/GameManager.java
> +        String newAnswer = numberGenerator.numberGenerate();
reset Answer라는 메소드 명에 의미가 드러나기 때문에 newAnswer에 할당하는 절차는 없어도 될 것 같습니다 :)

2021-12-02 04:50 UTC, sihyung92 commented on src/test/java/baseball/GameResultTest.java
> +public class GameResultTest {
테스트코드까지!! 👍

2021-12-02 11:41 UTC, bbeomgeun commented on src/main/java/baseball/Validation.java
> +        return false;
와, 제안해주신 코드 보니까 훨씬 간단하네요!
1. 바로 리턴해버리는 것을 염두했었는데, 최대한 이 코드의 리턴이 무엇을 의미하는지 네이밍을 통해 보여주는 것이 협업 시 좋을 것 같다는 생각에 최대한 나열해서 작성했던 것 같아요.
`return function()`
`int result = function() return result` 이런 식으로 풀어서 바로 리턴해보겠습니다!!

2. 스트림은 보기에도 직관적이고 간결해서 바로 공부하러 가보겠습니다 ㅎㅎ

2021-12-02 11:42 UTC, bbeomgeun commented on README.md
> +## 구현할 기능 목록
와 꿀팁 감사합니다!!!
2차, 3차과제에 바로 적용해보겠습니다 ㅎㅎㅎ

2021-12-02 11:46 UTC, bbeomgeun commented on src/main/java/utils/Constant.java
> +public class Constant {
"결합도는 객체지향에서 한 객체가 얼마나 다른 객체에 대한 정보를 갖고 있는가?"
"역할을 수행하는 책임을 가진 객체가 필요한 데이터를 직접 가지고 있는 것을 추구"
명심하겠습니다!
객체지향의 사실과 오해도 읽을 생각만하고 읽지 않았지만 바로 내일 도서관 가야겠네요 ㅎㅎ

2021-12-02 12:01 UTC, bbeomgeun commented on src/main/java/baseball/Validation.java
> +public class Validation {
아 그렇네요.. 별 생각 없이 클래스를 만들어서 구현했네요..

검증 클래스를 static으로 util클래스화 시키면 인스턴스를 생성하지 않고 바로 함수를 사용할 수 있을 것 같습니다.
static클래스로 만든다는 것은, 만약 사용하지 않는 클래스라도 처음 JVM이 로딩할 때 메모리에 적재되어 메모리를 사용한다는 단점이 있을 것 같습니다!

2021-12-02 12:21 UTC, bbeomgeun commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
우선 IllegalArgumentException은 의도치 않은 인자가 들어왔다는 의미기에, 컴파일 타임에 잡는 checked exception이 아닌 runtime exception을 상속한 unchecked exception이라고 생각됩니다.

그리고 throw 키워드는 예외를 발생시키는 키워드입니다. 그리고 throws 키워드는 자신을 호출하는 메서드에게 예외를 전달하여 예외처리를 떠맡기는 키워드입니다.

그렇다면?? 이 프로그램에서는 예외를 발생시키고 종료되야하므로 굳이 throws로 예외처리를 떠맡길 필요 없이 예외를 터뜨리고 종료되면 돼서 그런건가요?!!

2021-12-02 12:33 UTC, bbeomgeun commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
음 검증 로직에 대해선.. 
1. 요구사항에 사용자가 잘못된 입력값을 입력하면 exception을 발생시킨다.
2. 그 외에 예외가 발생할 곳이 추가적으로 없다고 판단했습니다.
따라서 당연하게도 사용자의 요청이 들어올 때만 검증해줬던 것 같습니다.

---

1. 유저의 입력이 직접 들어오는 부분에 바로 검증하는 것이 좋다고 생각되기도 하고
2. 바로 예외를 발생 시키지 말고 일단 입력을 받고 프로그램을 진행 시키다가, 해당 잘못된 입력을 사용할 때!! 검증을 해야되나? 라는 생각도 듭니다.
- 그렇다면 입력값을 갖고 볼, 스트라이크 로직을 수행할 때 검증도 동시에 일어나야 할까?
- 우선적으로 미리 입력 자체를 cut하면 내부까지 들어갈 필요가 없어질 것이다. 라는 생각이 듭니다.

이 부분은 멘토님의 피드백이나 생각을 듣고 싶습니다!

2021-12-02 12:42 UTC, bbeomgeun commented on src/main/java/utils/Constant.java
> +public class Constant {
아! 추가적으로 Constant의 DIGIT (자릿수) 항목은 여러 클래스에서 쓰이는데 이 경우 각 사용하는 클래스마다 선언해주는 것이 나을까요?
그렇다면 static으로 선언한 것도 풀어줘야 할 것 같은데 멘토님 의견 듣고 싶습니다!

2021-12-02 12:47 UTC, bbeomgeun commented on src/main/java/baseball/GameManager.java
> +    String answer;
앗 넵! 이 부분은 제가 마지막에 시간 되기 전 급하게 구현하느라 그냥 막 전역변수로 선언했습니다 ㅎㅎ..
밑에 requestProgress 부분에서 answer 객체에 접근하는 부분이 있어서 그냥 전역으로 후딱 선언해버렸습니다!

전역 answer 변수를 참조하는 여러 게임(run메서드)이 진행되면 공유 자원에 접근하는 꼴이 되어서 오류가 날 것 같다는 말씀으로 이해했는데 맞을까요?
같은 변수를 참조해서 어느 한 게임에서 정답을 맞춰서 reset해버리면 다른 게임의 answer도 바뀔 것 같다는 생각이 듭니다..!

2021-12-02 12:56 UTC, bbeomgeun commented on src/main/java/baseball/GameManager.java
> +    NumberGenerator numberGenerator = new NumberGenerator();
1. public은 전역에서 접근 가능
2. protected는 같은 패키지 or 다른 패키지여도 상속 받은 클래스
3. default는 같은 패키지
4. private은 같은 클래스의 차이로 알고 있습니다!

---

default일 경우, GameManager의 인스턴스를 생성한 후 외부에서 접근이 가능해서 의도치 않은 변경이 일어날 수 있을 것 같습니다. 그래서 private 멤버 변수에 getter, setter를 이용하는 것으로 알고 있구요.

그런데 제가 헷갈리는 점은 클래스 내에서 다른 클래스의 인스턴스를 생성해서 사용하는 것이 익숙하지 않아서 그런데, 
혹시 클래스의 멤버 변수와 저렇게 인스턴스를 생성하는 변수와 동일하게 생각해도 되나요?

```
class A {
  private 멤버 변수 // 외부에서 접근 불가능, getter setter 사용
}
```

2021-12-02 12:56 UTC, bbeomgeun commented on src/main/java/baseball/GameManager.java
> +        String newAnswer = numberGenerator.numberGenerate();
넵! 바로 리턴하겠습니다 ㅎㅎ

2021-12-02 12:56 UTC, bbeomgeun commented on src/test/java/baseball/GameResultTest.java
> +public class GameResultTest {
감사합니다 :)

2021-12-02 13:58 UTC, bbeomgeun commented on src/main/java/baseball/MessagePrint.java
> +    public void getResultMessage(int strikeCount, int ballCount) {
넵! 하나의 메서드에 여러 분기로 판단해서 출력하지 않고, 각 조건을 메서드로 분리해서 메서드만 호출하는 방식으로 고민해보겠습니다!

2021-12-02 15:01 UTC, sihyung92 commented on src/main/java/baseball/GameManager.java
> +    NumberGenerator numberGenerator = new NumberGenerator();
네 말씀하신 것처럼 멤버변수에 대한 직접 참조는 객체지향의 핵심 개념인 `캡슐화`를 저해하기 때문에 가급적 private으로 접근 제한을 하는 편입니다. 하나의 클래스가 아는 것이 많아질수록, 코드의 복잡도가 상승하는데요
여기서 `아는 것`은 `import문을 몇개나 하고 있는가?` 라고 보아도 무방합니다!

import의 개수만큼 해당 클래스는 '다른 클래스에 영향을 받는 클래스'가 됩니다. 이렇게 다른 클래스와 알고 있는 것이 많은 객체를 '결합도가 높다'고 표현하는데요, 변경 여파에 취약한 코드가 되므로 객체지향 패러다임에선 지양하고 있습니다. 그래서 어떤 클래스의 멤버 변수를 직접 참조하여 무언가 하려는 게 아니라 딱! 
그 역할을 하는 하나의 객체만 알고, 그 객체에게 메소드(행위)를 통해 요청하여 알맞은 응답을 받아 작업을 수행합니다.

왜 이런 얘기를 길게 했느냐 하면... 위의 내용에 비추어 getter와 setter는 안티패턴이라고 불리기도 합니다. 기껏 private 로 해놓았는데, `A.멤버;` 나 `A.get멤버();`, 또 `A.멤버 = 멤버1' 과 `A.멤버.set멤버(멤버1)`을 하는 것은 전혀 다를 것이 없기 때문입니당 

코딩을 하다보면 getter는 어쩔 수 없이 용인되는 경우가 많은데요, setter는 동일한 객체의 역할을 제대로 수행하지 못하게 하는 경우가 많아 최대한 지양됩니다. 객체의 상태를 변경(멤버변수를 변경)하고 싶다면 상황에 걸맞는 메소드를 호출해 상태가 변화되도록 유도합니다. 아래 글에서의 add()처럼요!
[setter에 대한 어떤 개발자분의 고찰](
https://codingdog.tistory.com/entry/setter-%EB%A5%BC-%EC%96%B8%EC%A0%9C-%EC%93%B0%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-%EC%A7%80%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B0%84%EB%8B%A8%ED%95%9C-%EC%83%9D%EA%B0%81)

---

질문하신 거에선 `저렇게 인스턴스를 생성하는 변수`가 어떤 것인지 잘 감이 오지 않네요? 
실제 코드에서와 같이 new를 통해 직접 할당하는 것과, setter로 바깥에서 주입해주는 객체간의 차이를 말씀하시는 거라면, 동일한 것이 맞습니다.

하지만 직접 할당 보다는 생성자를 통한 초기화가 더 권장됩니다. 생성자를 만들어 해당 필드들에 할당해주는 방식인데요, 생성자의 동작원리에 대해 모르신다면 한번 학습해보길 권합니다 :) 
초기 상태를 setter없이 주입해줄 수 있다는 장점이 있습니다.

혹시 이해 안되는 부분있다면 편하게 질문 주세요!

2021-12-03 01:20 UTC, sihyung92 commented on src/main/java/utils/Constant.java
> +public class Constant {
ㅎ_ㅎ 전 가장 이 상수를 가지고 있을만한 객체에 갖다놓고, public으로 열어줘 다른 객체에선 참조하는 식으로 많이 쓰는 편입니다. (다른 객체에서 참조할 필요가 없는 상수는 private로 꼭꼭 잠급니다. -> 대부분 메소드나 필드 같은 경우 private로 코딩을 먼저 진행한 후 이유가 있을 경우에만 접근제한자를 넓혀나가는 편입니다 : 캡슐화)

또 전 Constant 같은 Util클래스(static만 있는 클래스)는 주의해서 사용해야 한다고 생각해요~~
Constant객체는 다양한 이유로 변경될 것(SRP 위반)이고 지나치게 많은 객체를 알고 있게 될겁니다(결합도 증가). Constant 클래스의 이름을 Constant2로 변경했을 때 얼마나 많은 클래스의 코드를 고쳐주어야 할지 생각해보시면 결합도가 높았을 때의 문제가 체감됩니당 '_'

하지만 '은탄환은 없다(모든 케이스에 들어맞는 절대법칙은 없다)' 는 사실도 기억해주셔요. 정답은 없습니당! 유틸클래스가 옳은 답일 때도 있습니다. 각 방법을 다 사용해보고, 장점과 단점에 대해 인식하고, 필요할 때 적절한 방법론을 적용해주셔요

2021-12-03 01:22 UTC, sihyung92 commented on src/main/java/baseball/Validation.java
> +public class Validation {
약간 함정 질문이었는데요, 메모리적인 손해보다는 객체지향 패러다임에서 지향하는 패턴이기 때문에 말씀드렸습니다 😀  
Util 클래스에 관한 의견은 
https://github.com/REVENGE-WOOTECO/java-baseball-precourse/pull/6#discussion_r761583181
참고해주시고 또 util 클래스에 대해 검색해보셔요!

2021-12-03 02:00 UTC, sihyung92 commented on src/main/java/baseball/Validation.java
> +public class Validation {
참고로 위 예시에서 원시값타입(String input)을 비즈니스적으로 의미있는 객체(GameNumber)로 한꺼풀 감싼 것을 VO(Value Object)라고 합니다. 데이터를 전송하는 역할을 하는 Dto와 VO의 차이도 재미있는 주제니 찾아보시는것도 :)

여튼.. 처음엔 객체분리 하는게 되게 어려운데요(어떤 클래스를 만들어야 하는거지?, 추상화 기술), 요구사항에 빗대어 생각해보시면 어느정도 도움이 됩니다. 처음에 잘 되지 않으므로 절차적으로 코드가 동작하게 코딩을 해놓고(먼저 되게 만들어라) 요구사항을 읽어보면서 `이런 요구사항을 수행하는 역할을 하는 건 무엇일까?` 생각해보고 클래스로 분리해주시면 됩니다.

2021-12-03 02:16 UTC, sihyung92 commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
unchecked라서 굳이 throws할 필요 없다는 의미에서 드린 피드백이었어용 ㅎ_ㅎ 해도 checked와 달리 반드시 catch해줄 의무가 발생하지 않고요 
다만 해당 클래스의 코드까지 안 들어가보고 마우스 들이대서 체크할 때 throws를 명시해놓으면 그게 표시되니 좋긴 하다만.. 해당 이유가 아니라면  throws 할 필요가 없다고 생각합니당당

2021-12-03 02:20 UTC, sihyung92 commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
검증 로직에 관한 질문은 어느정도 
https://github.com/REVENGE-WOOTECO/java-baseball-precourse/pull/6#discussion_r761583566
여기서 암시되고 있긴 한데요, 
1. 핵심 도메인 로직이 수행되는 곳에서는 반드시
2. 가능하다면 입력단에서도 잘라주는 것이 성능상 이득이 있으므로(내부까지 들어가지 않으므로) 좋음
정도로 생각합니닷 ㅎ_ㅎ 전 1번을 위주로 코딩하고, 성능최적화가 필요한 상황이면 2번도 고려해봅니다.

2021-12-03 02:20 UTC, sihyung92 commented on src/main/java/baseball/GameManager.java
> +    String answer;
맞습니닷~~!!

2021-12-03 02:22 UTC, sihyung92 commented
설명이 부족한 부분이나 이해가 어려운 부분이 있으면 편하게 질문주세요!! 본인의 의견 주셔도 좋아용용

2021-12-03 04:59 UTC, bbeomgeun commented on src/main/java/utils/Constant.java
> +public class Constant {
와우 제가 고민하던 점을 뚫어주신 것 같습니다!
저도 최대한 private으로 생성하고 넓혀나가는 캡슐화 연습을 해보겠습니다.

그리고 Constant2 예시는 매우 체감이 되는게 이번 과제할 때 상수를 어디다 둘지 몰라서 application에 일단 임시적으로 선언하고 나중에 바꿨는데 그때 하나하나 사용한 클래스가서 패키지명이랑 바꿔줬던 기억이 납니다..

값진 의견 공유 감사합니다 :)

2021-12-03 05:47 UTC, bbeomgeun commented on src/main/java/baseball/Validation.java
> +public class Validation {
와.. 원시값 타입을 VO로 감싼 다음에, 해당 VO의 생성자 자체에서 검증을 해버리는 방법이 있군요!
VO로 감싸지 않으면 입력값 자체를 받을 때가 어떻게 보면 값이 생성되는 것이라 입력 부분에서 검증이 필요한데, VO를 사용해서 입력은 입력만 받고 검증을 분리해서 다음으로 넘길 수 있게 되었네요.

"검증 로직은 각각의 객체에 갖고 있는 것이 낫고 보통 생성자에서 진행한다"
"먼저 절차지향으로 생각하고, 리팩토링 하자"

2021-12-03 05:56 UTC, bbeomgeun commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
넵!! 의견 감사합니다 ㅎㅎ
그럼 혹시 
1. 핵심 도메인 로직이 수행되는 곳에서는 반드시

에 위에서 말씀해주신 도메인 객체 생성자 수행하는 것부터 로직 수행이라고 생각해도 될까요??

2021-12-03 06:21 UTC, bbeomgeun commented on src/main/java/baseball/GameManager.java
> +    NumberGenerator numberGenerator = new NumberGenerator();
setter에 관한 고찰 잘 읽었습니다 ㅎㅎ
'저렇게 인스턴스를 생성하는 변수'라고 표현한 것은

```
public class A  {
  private int memberNo; // 멤버 변수
  B otherClass = new B(); // 인스턴스를 생성하는 변수를 의미한 것입니다 ㅎㅎ
}
```

```
말씀하신건
public class A {
  private B otherClass;

 A(B b) {
  otherClass = b; // 외부에서 생성자 주입을 뜻하신게 맞나요??
  }
}
```


잘 생각해보면 클래스 내에서 List<Integer> list = new ArrayList()<>; 도 생성해서 쓰는데 
```
List<Integer> list = new ArrayList()<>; 
MyClass myClass = new MyClass();
```
동일하게 생각해도 되는게 맞죠??

바보 같아 보이실 수 있는데 왜 사용자 정의 클래스로 인스턴스를 생성하는 것에 접근 제어자를 쓰거나 다른 멤버 변수랑 같이 선언하는 건 이질감이 드는지 모르겠네요 ㅠㅠ
아마도 이렇게 클래스를 객체지향적으로 분리해서 다른 클래스에서 선언해서 사용하는 건 처음이라 그런가봐요..! 

그래서 여기 otherClass도 private으로 닫으면 좋겠다는 피드백이셨구요! 맞을까요??
```
public class A  {
  private int memberNo; // 멤버 변수
  private B otherClass = new B(); // 접근 제어자 추가
}
```

2021-12-03 10:34 UTC, bbeomgeun commented
1. util 클래스에서 message(문구), constant(상수)를 없애고 각자 쓰이는 클래스로 위임했습니다.
2. 리뷰해주신 것처럼 원시타입 input을 비즈니스 VO로 한번 감싸서 내부에서 검증을 진행했습니다.
- 이렇게 바꾸니 입력받는 클래스는 정말 입력만 받고, 중복되는 메서드도 제거되고, 의존성도 많이 제거된 것 같습니다.
3. 입력값 자체를 이용하지 않고 VO로 감싸면서 자연스럽게 다른 입력값인 1, 2도 VO로 관리해주었습니다.
4. 출력 클래스 로직에 strike와 ball 판단하던 로직을 리뷰대로 결과 VO로 감싸고, 메서드를 만들어서 리팩토링 해봤습니다.
- 다만 결과 VO는 사용자의 입력을 받고 ball과 strike를 감싸느라 매번 새로운 객체가 new로 생성될 것 같은데 혹시 여기에 대해 의견을 듣고 싶습니다!
5. 마지막 커밋에서 말씀해주신 것처럼 변수 private final로 바꿔봤습니다!
- gameManager가 게임에 필요한 클래스들을 생성하면 더 이상 바뀌지 않을 것이라 생각해서 final 키워드를 붙였는데 이렇게 생각해도 되는건가요?
---
딱 이것까지만 여쭤보고 이번 1차과제는 마무리 하겠습니다..! 
많이 바쁘실텐데 너무 질문 폭격을 한 것 같아서 염치없지만.. 리뷰해 주신거 보고 바꿔보니 의존하고 있던 패키지 제거되고 코드가 간결해지는 걸 보니 너무 재밌습니다 ㅠㅠ

2021-12-04 03:06 UTC, sihyung92 approved these changes
몇가지 코드에 피드백을 남겼습니다 :) 

### 1. 다만 결과 VO는 사용자의 입력을 받고 ball과 strike를 감싸느라 매번 새로운 객체가 new로 생성될 것 같은데 혹시 여기에 대해 의견을 듣고 싶습니다!

- 객체 생성비용은 개발자가 걱정하지 않아도 됩니다, 자바는 GC가 더이상 사용하지 않는 객체를 쓸어가주니까요 🙂 while문으로 스택오버플로우를 내거나 참조를 제거하지 않아 GC를 못하도록 하는 Memory Leak이 생길 수 도 있지만... 평소 코딩할 때는 객체생성비용은 매우 낮다고 여기시고 안심하고 찍어내세욧

### 2. gameManager가 게임에 필요한 클래스들을 생성하면 더 이상 바뀌지 않을 것이라 생각해서 final 키워드를 붙였는데 이렇게 생각해도 되는건가요?

- 네 final 키워드는 객체를 immutable로 만드는 제약사항입니다. 굳이 이런 제약을 거는 이유는, 불변성이 가지는 다양한 장점이 있기 때문이에요. '불변 객체' 혹은 immutable로 찾아보셔요! 가능한 경우 최대한의 제약사항(접근제어자, 불변성)을 걸어주는 것이 오히려 안전한 코딩습관이 될 수 있습니다 :) 

### 3. [List 와 사용자 정의객체 질문]
동일하게 생각해도 되는게 맞죠??

네! 자바에서 원시형타입을 제외하고 모든 타입은 Object를 상속하는 객체입니다. List나 직접 정의한 객체는 '남이 만들어놓은 것'이라는 차이정도만 있어요. 자주 만들다 보면 점점 친해질테니 많이 친해지시길 바라요ㅎ_ㅎ

### 4. 바보 같아 보이실 수 있는데 왜 사용자 정의 클래스로 인스턴스를 생성하는 것에 접근 제어자를 쓰거나 다른 멤버 변수랑 같이 선언하는 건 이질감이 드는지 모르겠네요 ㅠㅠ

백엔드 개발자한테 가장 중요한 자세는 `바보같은 질문은 없다` 라고 생각합니다~~ 백엔드 개발자가 알아야 할 분야는 한 명의 사람이 모두 알 수 없을 만큼 방대해요 🙂 질문 할 때마다 걱정이 들면 결국 '내가 아는 것' 위에서만 놀게 됩니다. 내가 질문하는 상대도 처음은 있었다는 걸 명심하시고, 걱정이 드신다면 그 걱정을 질문을 날카롭게 가다듬는데 사용하셔요! '현상' '내 기반지식' '내 가설' 을 구분하여 말해주면 대답하는 입장에서 굉장히 편해집니다 :) 

이 코멘트를 마지막으로 해당 PR은 close할게요. 다음주도 파이팅~~~!!

2021-12-04 03:06 UTC, sihyung92 commented on src/main/java/baseball/UserInput.java
> +    public String answerInput() throws IllegalArgumentException {
네에 맞습니다 :)

2021-12-04 03:06 UTC, sihyung92 commented on src/main/java/VO/InputNumbers.java
> +public class InputNumbers {
복수형 명사는 컬렉션을 암시합니다 ㅎ_ㅎ 내부적으로 InputNumber의 자료구조를 가지고 있을 것 같은 느낌을 주네요.
VO는 보통 단일 값을 포장하지만, 일급 컬렉션이라는 이름으로 VO를 포함한 자료구조 객체를 만들기도 합니다 ㅎ_ㅎ  일급컬렉션 설명은 갓졸두님의 블로그 포스팅으로 대체할게요
https://jojoldu.tistory.com/412

2021-12-04 03:06 UTC, sihyung92 commented on src/main/java/VO/ReplyNumber.java
> +public class ReplyNumber {
해당 객체는 의미를 가지는 상수값 두개와, 그에 대한 확인 로직밖에 없는데요
이런 경우 enum을 사용하면 1,2가 아닌 경우에 대한 예외처리 없이 특정 상수를 표현할 수 있습니다. enum에 대해 찾아보셔요 ㅎ_ㅎ

2021-12-04 03:06 UTC, sihyung92 commented on src/main/java/VO/ResultNumbers.java
> +    private final int strikeCnt;
static 필드 블록과 멤버 필드 블록은 가독성을 위해 한줄 띄는 편입니다 :)

2021-12-04 03:06 UTC, sihyung92 commented on src/main/java/baseball/GameManager.java
> +    String answer;
사용자 객체 뿐만 아니라 원시형 타입도 private로 상태를 숨겨주셔요 😌 외부객체에서 해당 객체가 정의한 방법(메소드) 의외로 맘대로 상태를 수정할 수 있다면 캡슐화가 깨집니다

2021-12-04 03:06 UTC, sihyung92 commented on src/main/java/baseball/GameManager.java
> +            } else if (reply.isExit()) {
else if 블록은 지양해주세요! 
http://mkseo.pe.kr/blog/?p=2631

2021-12-04 03:09 UTC, merged